// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.h.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>
#pragma once
#include "PragmaResult.h"
#include "PragmaPlayerApi.h"
#include "Dto/PragmaDelayedRpcDto.h"

#include "DemoDelayedServiceRaw.generated.h"

struct FPragmaMessageMetadata;

UCLASS(Transient)
class PRAGMASDK_API UDemoDelayedServiceRaw : public UPragmaPlayerApi
{
GENERATED_BODY()

public:

    void virtual OnInitialized() override;

    DECLARE_DELEGATE_TwoParams(FDelayedV1Delegate, TPragmaResult<FPragma_Delayed_DelayedV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void DelayedV1(const FPragma_Delayed_DelayedV1Request& Request, FDelayedV1Delegate Delegate) const;
    virtual void DelayedV1(const FPragma_Delayed_DelayedV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Delayed_DelayedV1Response>, const FPragmaMessageMetadata&)> Callback) const;
};

