// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.h.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>
#pragma once
#include "PragmaResult.h"
#include "PragmaPlayerApi.h"
#include "Dto/PragmaGameDataRpcDto.h"

#include "PragmaGameDataServiceRaw.generated.h"

struct FPragmaMessageMetadata;

UCLASS(Transient)
class PRAGMASDK_API UPragmaGameDataServiceRaw : public UPragmaPlayerApi
{
GENERATED_BODY()

public:

    void virtual OnInitialized() override;

    DECLARE_DELEGATE_TwoParams(FGetLoginDataV3Delegate, TPragmaResult<FPragma_GameData_GetLoginDataV3Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetLoginDataV3(const FPragma_GameData_GetLoginDataV3Request& Request, FGetLoginDataV3Delegate Delegate) const;
    virtual void GetLoginDataV3(const FPragma_GameData_GetLoginDataV3Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_GameData_GetLoginDataV3Response>, const FPragmaMessageMetadata&)> Callback) const;
};

