// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaAccountCommonDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaMatchmakingExtDto.h"

#include "PragmaMatchmakingRpcDto.generated.h"

// Forward declarations.
struct FPragma_Matchmaking_MatchmakingQueueKey;
struct FPragma_Matchmaking_MatchmakingFailureV1Notification;
struct FPragma_Matchmaking_QueueInfoV2;
struct FPragma_Matchmaking_GetMatchmakingInfoV2Response;
struct FPragma_Matchmaking_GetMatchmakingInfoV2Request;
struct FPragma_Matchmaking_LeaveMatchmakingV2Response;
struct FPragma_Matchmaking_LeaveMatchmakingV2Request;

//
// Source protos:
// pragma/matchmaking/matchmakingRpc.proto
//


//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Matchmaking_MatchmakingFailureReason : uint8
{
	UNSPECIFIED = 0,
	GAME_SERVER_VERSION_NO_LONGER_COMPATIBLE = 1,
};

//
// Messages.
//

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_MatchmakingQueueKey
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Matchmaking_ExtMatchmakingKey ExtMatchmakingKey;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameServerVersion;

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_MatchmakingQueueKey& Lhs, const FPragma_Matchmaking_MatchmakingQueueKey& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_MatchmakingQueueKey& Lhs, const FPragma_Matchmaking_MatchmakingQueueKey& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_MatchmakingFailureV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Matchmaking_MatchmakingFailureReason Reason{static_cast<EPragma_Matchmaking_MatchmakingFailureReason>(0)};

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_MatchmakingFailureV1Notification& Lhs, const FPragma_Matchmaking_MatchmakingFailureV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_MatchmakingFailureV1Notification& Lhs, const FPragma_Matchmaking_MatchmakingFailureV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_QueueInfoV2
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Matchmaking_MatchmakingQueueKey MatchmakingQueueKey;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 PartiesInQueue{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 PlayersInQueue{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 MatchablesInQueue{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 GameInstancesInQueue{0};

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_QueueInfoV2& Lhs, const FPragma_Matchmaking_QueueInfoV2& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_QueueInfoV2& Lhs, const FPragma_Matchmaking_QueueInfoV2& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_GetMatchmakingInfoV2Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Matchmaking_QueueInfoV2> QueueInfo;

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_GetMatchmakingInfoV2Response& Lhs, const FPragma_Matchmaking_GetMatchmakingInfoV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_GetMatchmakingInfoV2Response& Lhs, const FPragma_Matchmaking_GetMatchmakingInfoV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_GetMatchmakingInfoV2Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_GetMatchmakingInfoV2Request& Lhs, const FPragma_Matchmaking_GetMatchmakingInfoV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_GetMatchmakingInfoV2Request& Lhs, const FPragma_Matchmaking_GetMatchmakingInfoV2Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_LeaveMatchmakingV2Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_LeaveMatchmakingV2Response& Lhs, const FPragma_Matchmaking_LeaveMatchmakingV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_LeaveMatchmakingV2Response& Lhs, const FPragma_Matchmaking_LeaveMatchmakingV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_LeaveMatchmakingV2Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_LeaveMatchmakingV2Request& Lhs, const FPragma_Matchmaking_LeaveMatchmakingV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_LeaveMatchmakingV2Request& Lhs, const FPragma_Matchmaking_LeaveMatchmakingV2Request& Rhs);

