// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.cpp.mustache
// </auto-generated>

#include "PragmaFriendCommonDto.h"
#include "CoreMinimal.h"
#include "PragmaJson.h"



bool operator==(const FPragma_Friend_Presence& Lhs, const FPragma_Friend_Presence& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.PlayerId == Rhs.PlayerId
			&& Lhs.GameShardId == Rhs.GameShardId
			&& Lhs.GameTitleId == Rhs.GameTitleId
			&& Lhs.BasicPresence == Rhs.BasicPresence
			&& Lhs.Version == Rhs.Version
			&& Lhs.Ext == Rhs.Ext
;
}
bool operator!=(const FPragma_Friend_Presence& Lhs, const FPragma_Friend_Presence& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Friend_FriendOverview& Lhs, const FPragma_Friend_FriendOverview& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.SocialId == Rhs.SocialId
			&& Lhs.DisplayName == Rhs.DisplayName
;
}
bool operator!=(const FPragma_Friend_FriendOverview& Lhs, const FPragma_Friend_FriendOverview& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Friend_FriendListUpdates& Lhs, const FPragma_Friend_FriendListUpdates& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.FriendsAdded == Rhs.FriendsAdded
			&& Lhs.FriendsRemoved == Rhs.FriendsRemoved
			&& Lhs.ReceivedInvitesAdded == Rhs.ReceivedInvitesAdded
			&& Lhs.ReceivedInvitesRemoved == Rhs.ReceivedInvitesRemoved
			&& Lhs.SentInvitesAdded == Rhs.SentInvitesAdded
			&& Lhs.SentInvitesRemoved == Rhs.SentInvitesRemoved
			&& Lhs.Version == Rhs.Version
;
}
bool operator!=(const FPragma_Friend_FriendListUpdates& Lhs, const FPragma_Friend_FriendListUpdates& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Friend_Friend& Lhs, const FPragma_Friend_Friend& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.SocialId == Rhs.SocialId
			&& Lhs.PlayerId == Rhs.PlayerId
			&& Lhs.DisplayName == Rhs.DisplayName
			&& Lhs.Presences == Rhs.Presences
;
}
bool operator!=(const FPragma_Friend_Friend& Lhs, const FPragma_Friend_Friend& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Friend_FriendList& Lhs, const FPragma_Friend_FriendList& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Friends == Rhs.Friends
			&& Lhs.SentInvites == Rhs.SentInvites
			&& Lhs.ReceivedInvites == Rhs.ReceivedInvites
			&& Lhs.Version == Rhs.Version
;
}
bool operator!=(const FPragma_Friend_FriendList& Lhs, const FPragma_Friend_FriendList& Rhs)
{
	return !(Lhs == Rhs);
}
