// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.cpp.mustache
// </auto-generated>

#include "PragmaTelemetryRpcDto.h"
#include "CoreMinimal.h"
#include "PragmaJson.h"



bool operator==(const FPragma_Telemetry_EventsPartnerV1Response& Lhs, const FPragma_Telemetry_EventsPartnerV1Response& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_Telemetry_EventsPartnerV1Response& Lhs, const FPragma_Telemetry_EventsPartnerV1Response& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_EventPartnerV1Response& Lhs, const FPragma_Telemetry_EventPartnerV1Response& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_Telemetry_EventPartnerV1Response& Lhs, const FPragma_Telemetry_EventPartnerV1Response& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_PlayerEventsV1Response& Lhs, const FPragma_Telemetry_PlayerEventsV1Response& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_Telemetry_PlayerEventsV1Response& Lhs, const FPragma_Telemetry_PlayerEventsV1Response& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_PlayerEventV1Response& Lhs, const FPragma_Telemetry_PlayerEventV1Response& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_Telemetry_PlayerEventV1Response& Lhs, const FPragma_Telemetry_PlayerEventV1Response& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_TelemetryEvent& Lhs, const FPragma_Telemetry_TelemetryEvent& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Name == Rhs.Name
			&& Lhs.Json == Rhs.Json
;
}
bool operator!=(const FPragma_Telemetry_TelemetryEvent& Lhs, const FPragma_Telemetry_TelemetryEvent& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_SourcedEvent& Lhs, const FPragma_Telemetry_SourcedEvent& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.SourceId == Rhs.SourceId
			&& Lhs.Event == Rhs.Event
;
}
bool operator!=(const FPragma_Telemetry_SourcedEvent& Lhs, const FPragma_Telemetry_SourcedEvent& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_EventsPartnerV1Request& Lhs, const FPragma_Telemetry_EventsPartnerV1Request& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Events == Rhs.Events
;
}
bool operator!=(const FPragma_Telemetry_EventsPartnerV1Request& Lhs, const FPragma_Telemetry_EventsPartnerV1Request& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_EventPartnerV1Request& Lhs, const FPragma_Telemetry_EventPartnerV1Request& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.SourceId == Rhs.SourceId
			&& Lhs.Event == Rhs.Event
;
}
bool operator!=(const FPragma_Telemetry_EventPartnerV1Request& Lhs, const FPragma_Telemetry_EventPartnerV1Request& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_PlayerEventsV1Request& Lhs, const FPragma_Telemetry_PlayerEventsV1Request& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Events == Rhs.Events
;
}
bool operator!=(const FPragma_Telemetry_PlayerEventsV1Request& Lhs, const FPragma_Telemetry_PlayerEventsV1Request& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Telemetry_PlayerEventV1Request& Lhs, const FPragma_Telemetry_PlayerEventV1Request& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Event == Rhs.Event
;
}
bool operator!=(const FPragma_Telemetry_PlayerEventV1Request& Lhs, const FPragma_Telemetry_PlayerEventV1Request& Rhs)
{
	return !(Lhs == Rhs);
}
