// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.cpp.mustache
// </auto-generated>

#include "PragmaPartyRpcCommonDto.h"
#include "CoreMinimal.h"
#include "PragmaJson.h"



bool operator==(const FPragma_Party_BroadcastPartyMember& Lhs, const FPragma_Party_BroadcastPartyMember& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Ext == Rhs.Ext
			&& Lhs.PlayerId == Rhs.PlayerId
			&& Lhs.DisplayName == Rhs.DisplayName
			&& Lhs.IsReady == Rhs.IsReady
			&& Lhs.IsLeader == Rhs.IsLeader
			&& Lhs.SocialId == Rhs.SocialId
;
}
bool operator!=(const FPragma_Party_BroadcastPartyMember& Lhs, const FPragma_Party_BroadcastPartyMember& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Party_BroadcastParty& Lhs, const FPragma_Party_BroadcastParty& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.ExtBroadcastParty == Rhs.ExtBroadcastParty
			&& Lhs.ExtPrivatePlayer == Rhs.ExtPrivatePlayer
			&& Lhs.PartyId == Rhs.PartyId
			&& Lhs.PartyMembers == Rhs.PartyMembers
			&& Lhs.InviteCode == Rhs.InviteCode
			&& Lhs.PreferredGameServerZones == Rhs.PreferredGameServerZones
;
}
bool operator!=(const FPragma_Party_BroadcastParty& Lhs, const FPragma_Party_BroadcastParty& Rhs)
{
	return !(Lhs == Rhs);
}
