// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.h.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>
#pragma once
#include "PragmaResult.h"
#include "PragmaServerApi.h"
#include "Dto/PragmaInventoryRpcDto.h"

#include "PragmaInventoryPartnerServiceRaw.generated.h"

struct FPragmaMessageMetadata;

UCLASS(Transient)
class PRAGMASDK_API UPragmaInventoryPartnerServiceRaw : public UPragmaServerApi
{
GENERATED_BODY()

public:

    void virtual OnInitialized() override;

    DECLARE_DELEGATE_TwoParams(FDeletePlayerInventoryPartnerV1Delegate, TPragmaResult<FPragma_Inventory_DeletePlayerInventoryPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void DeletePlayerInventoryPartnerV1(const FPragma_Inventory_DeletePlayerInventoryPartnerV1Request& Request, FDeletePlayerInventoryPartnerV1Delegate Delegate) const;
    virtual void DeletePlayerInventoryPartnerV1(const FPragma_Inventory_DeletePlayerInventoryPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_DeletePlayerInventoryPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FClearPlayerInventoryCachePartnerV1Delegate, TPragmaResult<FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void ClearPlayerInventoryCachePartnerV1(const FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Request& Request, FClearPlayerInventoryCachePartnerV1Delegate Delegate) const;
    virtual void ClearPlayerInventoryCachePartnerV1(const FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FSyncEntitlementsPartnerV1Delegate, TPragmaResult<FPragma_Inventory_SyncEntitlementsPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void SyncEntitlementsPartnerV1(const FPragma_Inventory_SyncEntitlementsPartnerV1Request& Request, FSyncEntitlementsPartnerV1Delegate Delegate) const;
    virtual void SyncEntitlementsPartnerV1(const FPragma_Inventory_SyncEntitlementsPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_SyncEntitlementsPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FUpdateItemsPartnerV2Delegate, TPragmaResult<FPragma_Inventory_UpdateItemsPartnerV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void UpdateItemsPartnerV2(const FPragma_Inventory_UpdateItemsPartnerV2Request& Request, FUpdateItemsPartnerV2Delegate Delegate) const;
    virtual void UpdateItemsPartnerV2(const FPragma_Inventory_UpdateItemsPartnerV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_UpdateItemsPartnerV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FSimulateRewardsV2Delegate, TPragmaResult<FPragma_Inventory_SimulateRewardsV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void SimulateRewardsV2(const FPragma_Inventory_SimulateRewardsV2Request& Request, FSimulateRewardsV2Delegate Delegate) const;
    virtual void SimulateRewardsV2(const FPragma_Inventory_SimulateRewardsV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_SimulateRewardsV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGrantItemsPartnerV2Delegate, TPragmaResult<FPragma_Inventory_GrantItemsPartnerV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GrantItemsPartnerV2(const FPragma_Inventory_GrantItemsPartnerV2Request& Request, FGrantItemsPartnerV2Delegate Delegate) const;
    virtual void GrantItemsPartnerV2(const FPragma_Inventory_GrantItemsPartnerV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_GrantItemsPartnerV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FDestroyItemsPartnerV2Delegate, TPragmaResult<FPragma_Inventory_DestroyItemsPartnerV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void DestroyItemsPartnerV2(const FPragma_Inventory_DestroyItemsPartnerV2Request& Request, FDestroyItemsPartnerV2Delegate Delegate) const;
    virtual void DestroyItemsPartnerV2(const FPragma_Inventory_DestroyItemsPartnerV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_DestroyItemsPartnerV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetInventoryPartnerV2Delegate, TPragmaResult<FPragma_Inventory_GetInventoryPartnerV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetInventoryPartnerV2(const FPragma_Inventory_GetInventoryPartnerV2Request& Request, FGetInventoryPartnerV2Delegate Delegate) const;
    virtual void GetInventoryPartnerV2(const FPragma_Inventory_GetInventoryPartnerV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_GetInventoryPartnerV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FApplyInventoryOperationsPartnerV1Delegate, TPragmaResult<FPragma_Inventory_ApplyInventoryOperationsPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void ApplyInventoryOperationsPartnerV1(const FPragma_Inventory_ApplyInventoryOperationsPartnerV1Request& Request, FApplyInventoryOperationsPartnerV1Delegate Delegate) const;
    virtual void ApplyInventoryOperationsPartnerV1(const FPragma_Inventory_ApplyInventoryOperationsPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_ApplyInventoryOperationsPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetProviderEntitlementHistoryPartnerV1Delegate, TPragmaResult<FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetProviderEntitlementHistoryPartnerV1(const FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Request& Request, FGetProviderEntitlementHistoryPartnerV1Delegate Delegate) const;
    virtual void GetProviderEntitlementHistoryPartnerV1(const FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
};

