// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaGameInstancePartnerServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaGameInstancePartnerServiceRaw::OnInitialized()
{
    REGISTER_PRAGMA_GAME_EVENT(OnAddPlayersV1, FPragma_GameInstance_AddPlayersV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnGameInstanceEnteredMatchmakingV1, FPragma_GameInstance_GameInstanceEnteredMatchmakingV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnGameInstanceLeftMatchmakingV1, FPragma_GameInstance_GameInstanceLeftMatchmakingV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnPlayerDeclinedReconnectV1, FPragma_GameInstance_PlayerDeclinedReconnectV1Notification);
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaGameInstancePartnerServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(GetGameStartDataV1, FPragma_GameInstance_GetGameStartDataV1Request, FPragma_GameInstance_GetGameStartDataV1Response, FGetGameStartDataV1Delegate);
IMPL_PRAGMA_METHOD(UpdateGameInstanceV1, FPragma_GameInstance_UpdateGameInstanceV1Request, FPragma_GameInstance_UpdateGameInstanceV1Response, FUpdateGameInstanceV1Delegate);
IMPL_PRAGMA_METHOD(ConnectPlayersV1, FPragma_GameInstance_ConnectPlayersV1Request, FPragma_GameInstance_ConnectPlayersV1Response, FConnectPlayersV1Delegate);
IMPL_PRAGMA_METHOD(ConnectMorePlayersV1, FPragma_GameInstance_ConnectMorePlayersV1Request, FPragma_GameInstance_ConnectMorePlayersV1Response, FConnectMorePlayersV1Delegate);
IMPL_PRAGMA_METHOD(GameKeepAliveV1, FPragma_GameInstance_GameKeepAliveV1Request, FPragma_GameInstance_GameKeepAliveV1Response, FGameKeepAliveV1Delegate);
IMPL_PRAGMA_METHOD(EnterMatchmakingV1, FPragma_GameInstance_EnterMatchmakingV1Request, FPragma_GameInstance_EnterMatchmakingV1Response, FEnterMatchmakingV1Delegate);
IMPL_PRAGMA_METHOD(LeaveMatchmakingV1, FPragma_GameInstance_LeaveMatchmakingV1Request, FPragma_GameInstance_LeaveMatchmakingV1Response, FLeaveMatchmakingV1Delegate);
IMPL_PRAGMA_METHOD(RemovePlayersV1, FPragma_GameInstance_RemovePlayersV1Request, FPragma_GameInstance_RemovePlayersV1Response, FRemovePlayersV1Delegate);
IMPL_PRAGMA_METHOD(EndGameV1, FPragma_GameInstance_EndGameV1Request, FPragma_GameInstance_EndGameV1Response, FEndGameV1Delegate);
IMPL_PRAGMA_METHOD(VerifyPlayerPartnerV1, FPragma_GameInstance_VerifyPlayerPartnerV1Request, FPragma_GameInstance_VerifyPlayerPartnerV1Response, FVerifyPlayerPartnerV1Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
