// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaAccountCommonDto.h"
#include "Dto/PragmaDataRightsCommonDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaAccountRpcExtDto.h"
#include "Dto/PragmaErrorsDto.h"

#include "PragmaAccountRpcDto.generated.h"

// Forward declarations.
struct FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response;
struct FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request;
struct FPragma_Account_AddAccountToPlayerGroupPartnerV1Response;
struct FPragma_Account_AddAccountToPlayerGroupPartnerV1Request;
struct FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response;
struct FPragma_Account_UpdateEmailV1Response;
struct FPragma_Account_UpdateEmailV1Request;
struct FPragma_Account_UpdateDisplayNameV1Response;
struct FPragma_Account_UpdateDisplayNameV1Request;
struct FPragma_Account_GetAccountV1Request;
struct FPragma_Account_RemoveAccountTagsRequest;
struct FPragma_Account_RemoveAccountTagsPartnerV1Request;
struct FPragma_Account_AddAccountTagsRequest;
struct FPragma_Account_AddAccountTagsPartnerV1Request;
struct FPragma_Account_GetAccountTagsPartnerV1Request;
struct FPragma_Account_ViewTagsPartnerV1Request;
struct FPragma_Account_IdProviderDisplayNameSearch;
struct FPragma_Account_PlayerSearchFilter;
struct FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request;
struct FPragma_Account_IdProviderAccount;
struct FPragma_Account_GameIdentity;
struct FPragma_Account_GetAccountV1Response;
struct FPragma_Account_AccountTag;
struct FPragma_Account_AccountTagsBySocialId;
struct FPragma_Account_RemoveAccountTagsPartnerV1Response;
struct FPragma_Account_AddAccountTagsPartnerV1Response;
struct FPragma_Account_GetAccountTagsPartnerV1Response;
struct FPragma_Account_ViewTagsPartnerV1Response;
struct FPragma_Account_ViewSocialIdentityPartnerV2Request;
struct FPragma_Account_ProviderAccountId;
struct FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request;
struct FPragma_Account_SocialIdentity;
struct FPragma_Account_SocialIdentityWithPersonal;
struct FPragma_Account_ViewSocialIdentityPartnerV2Response;
struct FPragma_Account_GetSocialIdentitiesPartnerV1Response;
struct FPragma_Account_GetSocialIdentitiesPartnerV1Request;
struct FPragma_Account_PlayerIdentity;
struct FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response;
struct FPragma_Account_GetPlayerIdentitiesPartnerV1Response;
struct FPragma_Account_GetPlayerIdentitiesPartnerV1Request;
struct FPragma_Account_DeleteAccountPartnerV1Response;
struct FPragma_Account_DeleteAccountPartnerV1Request;
struct FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response;
struct FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request;
struct FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response;
struct FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request;
struct FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response;
struct FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request;
struct FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response;
struct FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request;
struct FPragma_Account_LinkIdentityProviderAccountV2Response;
struct FPragma_Account_IdProviderRequest;
struct FPragma_Account_LinkIdentityProviderAccountV2Request;
struct FPragma_Account_FederateRequest;
struct FPragma_Account_LinkIdentityProviderAccountPartnerV1Request;
struct FPragma_Account_PragmaTokens;
struct FPragma_Account_LinkIdentityProviderAccountPartnerV1Response;
struct FPragma_Account_RefreshTokensV1Response;
struct FPragma_Account_RefreshTokensV1Request;

//
// Source protos:
// pragma/account/accountRpc.proto
//


//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Account_IdProvider : uint8
{
	UNUSED = 0,
	UNSAFE = 1,
	EPIC = 2,
	DISCORD = 3,
	STEAM = 4,
	EMAIL = 5,
	GOOGLE = 6,
	PLAYSTATION = 7,
	TWITCH = 8,
	XBOX = 9,
	OKTA = 10,
	AUTH0 = 11,
	GOOGLEWORKSPACE = 12,
	CUSTOM = 100,
};

//
// Messages.
//

//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Account_SearchEmailVerified : uint8
{
	DISABLED = 0,
	UNVERIFIED = 1,
	VERIFIED = 2,
};

//
// Messages.
//

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PlayerGroupIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response& Lhs, const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response& Lhs, const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerGroupId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request& Lhs, const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request& Lhs, const FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AddAccountToPlayerGroupPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PlayerGroupIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AddAccountToPlayerGroupPartnerV1Response& Lhs, const FPragma_Account_AddAccountToPlayerGroupPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AddAccountToPlayerGroupPartnerV1Response& Lhs, const FPragma_Account_AddAccountToPlayerGroupPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AddAccountToPlayerGroupPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerGroupId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AddAccountToPlayerGroupPartnerV1Request& Lhs, const FPragma_Account_AddAccountToPlayerGroupPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AddAccountToPlayerGroupPartnerV1Request& Lhs, const FPragma_Account_AddAccountToPlayerGroupPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_PragmaAccountOverview> Accounts;

	UPROPERTY()
	int64 Count{0};

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response& Lhs, const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response& Lhs, const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UpdateEmailV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_UpdateEmailV1Response& Lhs, const FPragma_Account_UpdateEmailV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UpdateEmailV1Response& Lhs, const FPragma_Account_UpdateEmailV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UpdateEmailV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString EmailAddress;

};
PRAGMASDK_API bool operator==(const FPragma_Account_UpdateEmailV1Request& Lhs, const FPragma_Account_UpdateEmailV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UpdateEmailV1Request& Lhs, const FPragma_Account_UpdateEmailV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UpdateDisplayNameV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName UpdatedDisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Account_UpdateDisplayNameV1Response& Lhs, const FPragma_Account_UpdateDisplayNameV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UpdateDisplayNameV1Response& Lhs, const FPragma_Account_UpdateDisplayNameV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UpdateDisplayNameV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString RequestedDisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Account_UpdateDisplayNameV1Request& Lhs, const FPragma_Account_UpdateDisplayNameV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UpdateDisplayNameV1Request& Lhs, const FPragma_Account_UpdateDisplayNameV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetAccountV1Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetAccountV1Request& Lhs, const FPragma_Account_GetAccountV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetAccountV1Request& Lhs, const FPragma_Account_GetAccountV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RemoveAccountTagsRequest
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PragmaSocialIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> AccountTagIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RemoveAccountTagsRequest& Lhs, const FPragma_Account_RemoveAccountTagsRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RemoveAccountTagsRequest& Lhs, const FPragma_Account_RemoveAccountTagsRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RemoveAccountTagsPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_RemoveAccountTagsRequest Request;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RemoveAccountTagsPartnerV1Request& Lhs, const FPragma_Account_RemoveAccountTagsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RemoveAccountTagsPartnerV1Request& Lhs, const FPragma_Account_RemoveAccountTagsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AddAccountTagsRequest
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PragmaSocialIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> AccountTags;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AddAccountTagsRequest& Lhs, const FPragma_Account_AddAccountTagsRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AddAccountTagsRequest& Lhs, const FPragma_Account_AddAccountTagsRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AddAccountTagsPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_AddAccountTagsRequest Request;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AddAccountTagsPartnerV1Request& Lhs, const FPragma_Account_AddAccountTagsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AddAccountTagsPartnerV1Request& Lhs, const FPragma_Account_AddAccountTagsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetAccountTagsPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PragmaSocialIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetAccountTagsPartnerV1Request& Lhs, const FPragma_Account_GetAccountTagsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetAccountTagsPartnerV1Request& Lhs, const FPragma_Account_GetAccountTagsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_ViewTagsPartnerV1Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_ViewTagsPartnerV1Request& Lhs, const FPragma_Account_ViewTagsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_ViewTagsPartnerV1Request& Lhs, const FPragma_Account_ViewTagsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_IdProviderDisplayNameSearch
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString IdProvider;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString FullDisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Account_IdProviderDisplayNameSearch& Lhs, const FPragma_Account_IdProviderDisplayNameSearch& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_IdProviderDisplayNameSearch& Lhs, const FPragma_Account_IdProviderDisplayNameSearch& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_PlayerSearchFilter
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> AccountTagIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> ExcludedPlayerGroupIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PlayerGroupIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> ExcludedAccountTagIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> IdProviders;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Account_SearchEmailVerified SearchEmailVerified{static_cast<EPragma_Account_SearchEmailVerified>(0)};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString IdProviderAccountId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString EmailAddress;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_IdProviderDisplayNameSearch IdProviderDisplayNameSearch;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaFullDisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_PlayerSearchFilter& Lhs, const FPragma_Account_PlayerSearchFilter& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_PlayerSearchFilter& Lhs, const FPragma_Account_PlayerSearchFilter& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_PlayerSearchFilter Filter;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 PageIndex{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 PageSize{0};

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request& Lhs, const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request& Lhs, const FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_IdProviderAccount
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString IdProviderType;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString AccountId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName ProviderDisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Account_IdProviderAccount& Lhs, const FPragma_Account_IdProviderAccount& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_IdProviderAccount& Lhs, const FPragma_Account_IdProviderAccount& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GameIdentity
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaPlayerId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GameIdentity& Lhs, const FPragma_Account_GameIdentity& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GameIdentity& Lhs, const FPragma_Account_GameIdentity& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetAccountV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString EmailAddress;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool EmailVerified{false};

	UPROPERTY()
	int64 AccountCreatedTimestampMillis{0};

	UPROPERTY()
	int64 LastLoginTimestampMillis{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName DisplayName;

	UPROPERTY()
	int64 LastDisplayNameUpdateTimestampMillis{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_GameIdentity> GameIdentities;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_IdProviderAccount> IdProviderAccounts;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetAccountV1Response& Lhs, const FPragma_Account_GetAccountV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetAccountV1Response& Lhs, const FPragma_Account_GetAccountV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AccountTag
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString TagId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Tag;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AccountTag& Lhs, const FPragma_Account_AccountTag& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AccountTag& Lhs, const FPragma_Account_AccountTag& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AccountTagsBySocialId
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTag> AccountTags;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AccountTagsBySocialId& Lhs, const FPragma_Account_AccountTagsBySocialId& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AccountTagsBySocialId& Lhs, const FPragma_Account_AccountTagsBySocialId& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RemoveAccountTagsPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTagsBySocialId> AccountTagsBySocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RemoveAccountTagsPartnerV1Response& Lhs, const FPragma_Account_RemoveAccountTagsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RemoveAccountTagsPartnerV1Response& Lhs, const FPragma_Account_RemoveAccountTagsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_AddAccountTagsPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTagsBySocialId> AccountTagsBySocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_AddAccountTagsPartnerV1Response& Lhs, const FPragma_Account_AddAccountTagsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_AddAccountTagsPartnerV1Response& Lhs, const FPragma_Account_AddAccountTagsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetAccountTagsPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTagsBySocialId> AccountTagsBySocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetAccountTagsPartnerV1Response& Lhs, const FPragma_Account_GetAccountTagsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetAccountTagsPartnerV1Response& Lhs, const FPragma_Account_GetAccountTagsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_ViewTagsPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTag> AccountTags;

};
PRAGMASDK_API bool operator==(const FPragma_Account_ViewTagsPartnerV1Response& Lhs, const FPragma_Account_ViewTagsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_ViewTagsPartnerV1Response& Lhs, const FPragma_Account_ViewTagsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_ViewSocialIdentityPartnerV2Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_ViewSocialIdentityPartnerV2Request& Lhs, const FPragma_Account_ViewSocialIdentityPartnerV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_ViewSocialIdentityPartnerV2Request& Lhs, const FPragma_Account_ViewSocialIdentityPartnerV2Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_ProviderAccountId
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString IdProviderType;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ProviderAccountId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_ProviderAccountId& Lhs, const FPragma_Account_ProviderAccountId& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_ProviderAccountId& Lhs, const FPragma_Account_ProviderAccountId& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_ProviderAccountId> ProviderAccountIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Lhs, const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Lhs, const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_SocialIdentity
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName PragmaDisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_GameIdentity> GameIdentities;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_IdProviderAccount> IdProviderAccounts;

};
PRAGMASDK_API bool operator==(const FPragma_Account_SocialIdentity& Lhs, const FPragma_Account_SocialIdentity& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_SocialIdentity& Lhs, const FPragma_Account_SocialIdentity& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_SocialIdentityWithPersonal
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_SocialIdentity SocialIdentity;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaPersonalId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_AccountTag> Tags;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString EmailAddress;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool EmailVerified{false};

	UPROPERTY()
	int64 CreatedTimestampMillis{0};

	UPROPERTY()
	int64 LastLoginTimestampMillis{0};

};
PRAGMASDK_API bool operator==(const FPragma_Account_SocialIdentityWithPersonal& Lhs, const FPragma_Account_SocialIdentityWithPersonal& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_SocialIdentityWithPersonal& Lhs, const FPragma_Account_SocialIdentityWithPersonal& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_ViewSocialIdentityPartnerV2Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_SocialIdentityWithPersonal SocialIdentity;

};
PRAGMASDK_API bool operator==(const FPragma_Account_ViewSocialIdentityPartnerV2Response& Lhs, const FPragma_Account_ViewSocialIdentityPartnerV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_ViewSocialIdentityPartnerV2Response& Lhs, const FPragma_Account_ViewSocialIdentityPartnerV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetSocialIdentitiesPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_SocialIdentity> SocialIdentities;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_BatchRequestFailure> Failures;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetSocialIdentitiesPartnerV1Response& Lhs, const FPragma_Account_GetSocialIdentitiesPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetSocialIdentitiesPartnerV1Response& Lhs, const FPragma_Account_GetSocialIdentitiesPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetSocialIdentitiesPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> SocialIds;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetSocialIdentitiesPartnerV1Request& Lhs, const FPragma_Account_GetSocialIdentitiesPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetSocialIdentitiesPartnerV1Request& Lhs, const FPragma_Account_GetSocialIdentitiesPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_PlayerIdentity
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaPlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName PragmaDisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_IdProviderAccount> IdProviderAccounts;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_PlayerIdentity& Lhs, const FPragma_Account_PlayerIdentity& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_PlayerIdentity& Lhs, const FPragma_Account_PlayerIdentity& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_PlayerIdentity> PlayerIdentities;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response& Lhs, const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response& Lhs, const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPlayerIdentitiesPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Account_PlayerIdentity> PlayerIdentities;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_BatchRequestFailure> Failures;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPlayerIdentitiesPartnerV1Response& Lhs, const FPragma_Account_GetPlayerIdentitiesPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPlayerIdentitiesPartnerV1Response& Lhs, const FPragma_Account_GetPlayerIdentitiesPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPlayerIdentitiesPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PlayerIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPlayerIdentitiesPartnerV1Request& Lhs, const FPragma_Account_GetPlayerIdentitiesPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPlayerIdentitiesPartnerV1Request& Lhs, const FPragma_Account_GetPlayerIdentitiesPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_DeleteAccountPartnerV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_DeleteAccountPartnerV1Response& Lhs, const FPragma_Account_DeleteAccountPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_DeleteAccountPartnerV1Response& Lhs, const FPragma_Account_DeleteAccountPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_DeleteAccountPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_DeleteAccountPartnerV1Request& Lhs, const FPragma_Account_DeleteAccountPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_DeleteAccountPartnerV1Request& Lhs, const FPragma_Account_DeleteAccountPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString DisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Discriminator;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response& Lhs, const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response& Lhs, const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaPlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Lhs, const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Lhs, const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaPlayerId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response& Lhs, const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response& Lhs, const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString DisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Discriminator;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Lhs, const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Lhs, const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName DisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response& Lhs, const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response& Lhs, const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request& Lhs, const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request& Lhs, const FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response& Lhs, const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response& Lhs, const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString IdProvider;

};
PRAGMASDK_API bool operator==(const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request& Lhs, const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request& Lhs, const FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_LinkIdentityProviderAccountV2Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Account_LinkIdentityProviderAccountV2Response& Lhs, const FPragma_Account_LinkIdentityProviderAccountV2Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_LinkIdentityProviderAccountV2Response& Lhs, const FPragma_Account_LinkIdentityProviderAccountV2Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_IdProviderRequest
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ProviderId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ProviderToken;

};
PRAGMASDK_API bool operator==(const FPragma_Account_IdProviderRequest& Lhs, const FPragma_Account_IdProviderRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_IdProviderRequest& Lhs, const FPragma_Account_IdProviderRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_LinkIdentityProviderAccountV2Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_IdProviderRequest NewProvider;

};
PRAGMASDK_API bool operator==(const FPragma_Account_LinkIdentityProviderAccountV2Request& Lhs, const FPragma_Account_LinkIdentityProviderAccountV2Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_LinkIdentityProviderAccountV2Request& Lhs, const FPragma_Account_LinkIdentityProviderAccountV2Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_FederateRequest
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_IdProviderRequest ExistingProvider;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_IdProviderRequest NewProvider;

};
PRAGMASDK_API bool operator==(const FPragma_Account_FederateRequest& Lhs, const FPragma_Account_FederateRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_FederateRequest& Lhs, const FPragma_Account_FederateRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_LinkIdentityProviderAccountPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_FederateRequest Request;

};
PRAGMASDK_API bool operator==(const FPragma_Account_LinkIdentityProviderAccountPartnerV1Request& Lhs, const FPragma_Account_LinkIdentityProviderAccountPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_LinkIdentityProviderAccountPartnerV1Request& Lhs, const FPragma_Account_LinkIdentityProviderAccountPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_PragmaTokens
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaGameToken;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PragmaSocialToken;

};
PRAGMASDK_API bool operator==(const FPragma_Account_PragmaTokens& Lhs, const FPragma_Account_PragmaTokens& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_PragmaTokens& Lhs, const FPragma_Account_PragmaTokens& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_LinkIdentityProviderAccountPartnerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_PragmaTokens Tokens;

};
PRAGMASDK_API bool operator==(const FPragma_Account_LinkIdentityProviderAccountPartnerV1Response& Lhs, const FPragma_Account_LinkIdentityProviderAccountPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_LinkIdentityProviderAccountPartnerV1Response& Lhs, const FPragma_Account_LinkIdentityProviderAccountPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RefreshTokensV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_PragmaTokens PragmaTokens;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RefreshTokensV1Response& Lhs, const FPragma_Account_RefreshTokensV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RefreshTokensV1Response& Lhs, const FPragma_Account_RefreshTokensV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Account_RefreshTokensV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_PragmaTokens PragmaTokens;

};
PRAGMASDK_API bool operator==(const FPragma_Account_RefreshTokensV1Request& Lhs, const FPragma_Account_RefreshTokensV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Account_RefreshTokensV1Request& Lhs, const FPragma_Account_RefreshTokensV1Request& Rhs);

