// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.h.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>
#pragma once
#include "PragmaResult.h"
#include "PragmaPlayerApi.h"
#include "Dto/PragmaAccountRpcDto.h"

#include "PragmaAccountServiceRaw.generated.h"

struct FPragmaMessageMetadata;

UCLASS(Transient)
class PRAGMASDK_API UPragmaAccountServiceRaw : public UPragmaPlayerApi
{
GENERATED_BODY()

public:

    void virtual OnInitialized() override;

    DECLARE_DELEGATE_TwoParams(FRefreshTokensV1Delegate, TPragmaResult<FPragma_Account_RefreshTokensV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void RefreshTokensV1(const FPragma_Account_RefreshTokensV1Request& Request, FRefreshTokensV1Delegate Delegate) const;
    virtual void RefreshTokensV1(const FPragma_Account_RefreshTokensV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_RefreshTokensV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FLinkIdentityProviderAccountV2Delegate, TPragmaResult<FPragma_Account_LinkIdentityProviderAccountV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void LinkIdentityProviderAccountV2(const FPragma_Account_LinkIdentityProviderAccountV2Request& Request, FLinkIdentityProviderAccountV2Delegate Delegate) const;
    virtual void LinkIdentityProviderAccountV2(const FPragma_Account_LinkIdentityProviderAccountV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_LinkIdentityProviderAccountV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetPragmaPlayerIdForDisplayNameV1Delegate, TPragmaResult<FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetPragmaPlayerIdForDisplayNameV1(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Request, FGetPragmaPlayerIdForDisplayNameV1Delegate Delegate) const;
    virtual void GetPragmaPlayerIdForDisplayNameV1(const FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetDisplayNameForPragmaPlayerIdV1Delegate, TPragmaResult<FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetDisplayNameForPragmaPlayerIdV1(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Request, FGetDisplayNameForPragmaPlayerIdV1Delegate Delegate) const;
    virtual void GetDisplayNameForPragmaPlayerIdV1(const FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetPragmaPlayerIdsForProviderIdsV2Delegate, TPragmaResult<FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetPragmaPlayerIdsForProviderIdsV2(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Request, FGetPragmaPlayerIdsForProviderIdsV2Delegate Delegate) const;
    virtual void GetPragmaPlayerIdsForProviderIdsV2(const FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetAccountV1Delegate, TPragmaResult<FPragma_Account_GetAccountV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetAccountV1(const FPragma_Account_GetAccountV1Request& Request, FGetAccountV1Delegate Delegate) const;
    virtual void GetAccountV1(const FPragma_Account_GetAccountV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_GetAccountV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FUpdateDisplayNameV1Delegate, TPragmaResult<FPragma_Account_UpdateDisplayNameV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void UpdateDisplayNameV1(const FPragma_Account_UpdateDisplayNameV1Request& Request, FUpdateDisplayNameV1Delegate Delegate) const;
    virtual void UpdateDisplayNameV1(const FPragma_Account_UpdateDisplayNameV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_UpdateDisplayNameV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FUpdateEmailV1Delegate, TPragmaResult<FPragma_Account_UpdateEmailV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void UpdateEmailV1(const FPragma_Account_UpdateEmailV1Request& Request, FUpdateEmailV1Delegate Delegate) const;
    virtual void UpdateEmailV1(const FPragma_Account_UpdateEmailV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_Account_UpdateEmailV1Response>, const FPragmaMessageMetadata&)> Callback) const;
};

