// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaAccountCommonDto.h"
#include "Dto/PragmaPartyRpcCommonDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaPartyRpcExtDto.h"

#include "PragmaPartyRpcDto.generated.h"

// Forward declarations.
struct FPragma_Party_RemovedV1Notification;
struct FPragma_Party_PartyClientVersionMismatchV1Notification;
struct FPragma_Party_GameClientNotSupportedV1Notification;
struct FPragma_Party_InviteResponseV1Notification;
struct FPragma_Party_InviterInfo;
struct FPragma_Party_InviteReceivedV1Notification;
struct FPragma_Party_PartyDetailsV1Notification;
struct FPragma_Party_EnterMatchmakingV1Response;
struct FPragma_Party_EnterMatchmakingV1Request;
struct FPragma_Party_DevelopmentOverrideGameServerVersionV1Response;
struct FPragma_Party_DevelopmentOverrideGameServerVersionV1Request;
struct FPragma_Party_UpdatePartyV1Response;
struct FPragma_Party_UpdatePartyV1Request;
struct FPragma_Party_UpdatePartyPlayerV1Response;
struct FPragma_Party_UpdatePartyPlayerV1Request;
struct FPragma_Party_SetPreferredGameServerZonesV1Response;
struct FPragma_Party_SetGameServerZoneToPingV1Response;
struct FPragma_Party_SetGameServerZoneToPingV1Request;
struct FPragma_Party_SetPreferredGameServerZonesV1Request;
struct FPragma_Party_SetReadyStateV1Response;
struct FPragma_Party_SetReadyStateV1Request;
struct FPragma_Party_LeaveV1Response;
struct FPragma_Party_LeaveV1Request;
struct FPragma_Party_KickV1Response;
struct FPragma_Party_KickV1Request;
struct FPragma_Party_AssignPartyLeaderV1Response;
struct FPragma_Party_AssignPartyLeaderV1Request;
struct FPragma_Party_JoinWithPartyIdV1Response;
struct FPragma_Party_JoinWithPartyIdV1Request;
struct FPragma_Party_JoinWithInviteCodeV1Response;
struct FPragma_Party_JoinWithInviteCodeV1Request;
struct FPragma_Party_RespondToInviteV1Response;
struct FPragma_Party_RespondToInviteV1Request;
struct FPragma_Party_SendInviteV1Response;
struct FPragma_Party_SendInviteV1Request;
struct FPragma_Party_CreateV1Response;
struct FPragma_Party_CreateV1Request;

//
// Source protos:
// pragma/party/partyRpc.proto
//


//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_RemovalReason : uint8
{
	REMOVAL_REASON_UNSPECIFIED = 0,
	KICKED = 3,
	LEFT = 4,
	DISCONNECTED = 5,
};

//
// Messages.
//

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_RemovedV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PartyId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Party_RemovalReason RemovalReason{static_cast<EPragma_Party_RemovalReason>(0)};

};
PRAGMASDK_API bool operator==(const FPragma_Party_RemovedV1Notification& Lhs, const FPragma_Party_RemovedV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_RemovedV1Notification& Lhs, const FPragma_Party_RemovedV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_PartyClientVersionMismatchV1Notification
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_PartyClientVersionMismatchV1Notification& Lhs, const FPragma_Party_PartyClientVersionMismatchV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_PartyClientVersionMismatchV1Notification& Lhs, const FPragma_Party_PartyClientVersionMismatchV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_GameClientNotSupportedV1Notification
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_GameClientNotSupportedV1Notification& Lhs, const FPragma_Party_GameClientNotSupportedV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_GameClientNotSupportedV1Notification& Lhs, const FPragma_Party_GameClientNotSupportedV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_InviteResponseV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool Accepted{false};

};
PRAGMASDK_API bool operator==(const FPragma_Party_InviteResponseV1Notification& Lhs, const FPragma_Party_InviteResponseV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_InviteResponseV1Notification& Lhs, const FPragma_Party_InviteResponseV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_InviterInfo
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName DisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Party_InviterInfo& Lhs, const FPragma_Party_InviterInfo& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_InviterInfo& Lhs, const FPragma_Party_InviterInfo& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_InviteReceivedV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_InviterInfo InviterInfo;

};
PRAGMASDK_API bool operator==(const FPragma_Party_InviteReceivedV1Notification& Lhs, const FPragma_Party_InviteReceivedV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_InviteReceivedV1Notification& Lhs, const FPragma_Party_InviteReceivedV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_PartyDetailsV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_PartyDetailsV1Notification& Lhs, const FPragma_Party_PartyDetailsV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_PartyDetailsV1Notification& Lhs, const FPragma_Party_PartyDetailsV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_EnterMatchmakingV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_EnterMatchmakingV1Response& Lhs, const FPragma_Party_EnterMatchmakingV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_EnterMatchmakingV1Response& Lhs, const FPragma_Party_EnterMatchmakingV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_EnterMatchmakingV1Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_EnterMatchmakingV1Request& Lhs, const FPragma_Party_EnterMatchmakingV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_EnterMatchmakingV1Request& Lhs, const FPragma_Party_EnterMatchmakingV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_DevelopmentOverrideGameServerVersionV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_DevelopmentOverrideGameServerVersionV1Response& Lhs, const FPragma_Party_DevelopmentOverrideGameServerVersionV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_DevelopmentOverrideGameServerVersionV1Response& Lhs, const FPragma_Party_DevelopmentOverrideGameServerVersionV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_DevelopmentOverrideGameServerVersionV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameServerVersion;

};
PRAGMASDK_API bool operator==(const FPragma_Party_DevelopmentOverrideGameServerVersionV1Request& Lhs, const FPragma_Party_DevelopmentOverrideGameServerVersionV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_DevelopmentOverrideGameServerVersionV1Request& Lhs, const FPragma_Party_DevelopmentOverrideGameServerVersionV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_UpdatePartyV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_UpdatePartyV1Response& Lhs, const FPragma_Party_UpdatePartyV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_UpdatePartyV1Response& Lhs, const FPragma_Party_UpdatePartyV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_UpdatePartyV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtUpdatePartyRequest RequestExt;

};
PRAGMASDK_API bool operator==(const FPragma_Party_UpdatePartyV1Request& Lhs, const FPragma_Party_UpdatePartyV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_UpdatePartyV1Request& Lhs, const FPragma_Party_UpdatePartyV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_UpdatePartyPlayerV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_UpdatePartyPlayerV1Response& Lhs, const FPragma_Party_UpdatePartyPlayerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_UpdatePartyPlayerV1Response& Lhs, const FPragma_Party_UpdatePartyPlayerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_UpdatePartyPlayerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtUpdatePartyPlayerRequest RequestExt;

};
PRAGMASDK_API bool operator==(const FPragma_Party_UpdatePartyPlayerV1Request& Lhs, const FPragma_Party_UpdatePartyPlayerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_UpdatePartyPlayerV1Request& Lhs, const FPragma_Party_UpdatePartyPlayerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetPreferredGameServerZonesV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetPreferredGameServerZonesV1Response& Lhs, const FPragma_Party_SetPreferredGameServerZonesV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetPreferredGameServerZonesV1Response& Lhs, const FPragma_Party_SetPreferredGameServerZonesV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetGameServerZoneToPingV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetGameServerZoneToPingV1Response& Lhs, const FPragma_Party_SetGameServerZoneToPingV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetGameServerZoneToPingV1Response& Lhs, const FPragma_Party_SetGameServerZoneToPingV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetGameServerZoneToPingV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TMap<FString, int32> GameServerZoneToPing;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetGameServerZoneToPingV1Request& Lhs, const FPragma_Party_SetGameServerZoneToPingV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetGameServerZoneToPingV1Request& Lhs, const FPragma_Party_SetGameServerZoneToPingV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetPreferredGameServerZonesV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PreferredGameServerZones;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetPreferredGameServerZonesV1Request& Lhs, const FPragma_Party_SetPreferredGameServerZonesV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetPreferredGameServerZonesV1Request& Lhs, const FPragma_Party_SetPreferredGameServerZonesV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetReadyStateV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetReadyStateV1Response& Lhs, const FPragma_Party_SetReadyStateV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetReadyStateV1Response& Lhs, const FPragma_Party_SetReadyStateV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SetReadyStateV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool Ready{false};

};
PRAGMASDK_API bool operator==(const FPragma_Party_SetReadyStateV1Request& Lhs, const FPragma_Party_SetReadyStateV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SetReadyStateV1Request& Lhs, const FPragma_Party_SetReadyStateV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_LeaveV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_LeaveV1Response& Lhs, const FPragma_Party_LeaveV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_LeaveV1Response& Lhs, const FPragma_Party_LeaveV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_LeaveV1Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_LeaveV1Request& Lhs, const FPragma_Party_LeaveV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_LeaveV1Request& Lhs, const FPragma_Party_LeaveV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_KickV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_KickV1Response& Lhs, const FPragma_Party_KickV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_KickV1Response& Lhs, const FPragma_Party_KickV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_KickV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

};
PRAGMASDK_API bool operator==(const FPragma_Party_KickV1Request& Lhs, const FPragma_Party_KickV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_KickV1Request& Lhs, const FPragma_Party_KickV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_AssignPartyLeaderV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_AssignPartyLeaderV1Response& Lhs, const FPragma_Party_AssignPartyLeaderV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_AssignPartyLeaderV1Response& Lhs, const FPragma_Party_AssignPartyLeaderV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_AssignPartyLeaderV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

};
PRAGMASDK_API bool operator==(const FPragma_Party_AssignPartyLeaderV1Request& Lhs, const FPragma_Party_AssignPartyLeaderV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_AssignPartyLeaderV1Request& Lhs, const FPragma_Party_AssignPartyLeaderV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_JoinWithPartyIdV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_JoinWithPartyIdV1Response& Lhs, const FPragma_Party_JoinWithPartyIdV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_JoinWithPartyIdV1Response& Lhs, const FPragma_Party_JoinWithPartyIdV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_JoinWithPartyIdV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtPlayerJoinRequest RequestExt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameClientVersion;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PartyId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TMap<FString, int32> GameServerZoneToPing;

};
PRAGMASDK_API bool operator==(const FPragma_Party_JoinWithPartyIdV1Request& Lhs, const FPragma_Party_JoinWithPartyIdV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_JoinWithPartyIdV1Request& Lhs, const FPragma_Party_JoinWithPartyIdV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_JoinWithInviteCodeV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_JoinWithInviteCodeV1Response& Lhs, const FPragma_Party_JoinWithInviteCodeV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_JoinWithInviteCodeV1Response& Lhs, const FPragma_Party_JoinWithInviteCodeV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_JoinWithInviteCodeV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtPlayerJoinRequest RequestExt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteCode;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameClientVersion;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TMap<FString, int32> GameServerZoneToPing;

};
PRAGMASDK_API bool operator==(const FPragma_Party_JoinWithInviteCodeV1Request& Lhs, const FPragma_Party_JoinWithInviteCodeV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_JoinWithInviteCodeV1Request& Lhs, const FPragma_Party_JoinWithInviteCodeV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_RespondToInviteV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_RespondToInviteV1Response& Lhs, const FPragma_Party_RespondToInviteV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_RespondToInviteV1Response& Lhs, const FPragma_Party_RespondToInviteV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_RespondToInviteV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtPlayerJoinRequest RequestExt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool Accepted{false};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameClientVersion;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TMap<FString, int32> GameServerZoneToPing;

};
PRAGMASDK_API bool operator==(const FPragma_Party_RespondToInviteV1Request& Lhs, const FPragma_Party_RespondToInviteV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_RespondToInviteV1Request& Lhs, const FPragma_Party_RespondToInviteV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SendInviteV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteId;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SendInviteV1Response& Lhs, const FPragma_Party_SendInviteV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SendInviteV1Response& Lhs, const FPragma_Party_SendInviteV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_SendInviteV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteePlayerId;

};
PRAGMASDK_API bool operator==(const FPragma_Party_SendInviteV1Request& Lhs, const FPragma_Party_SendInviteV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_SendInviteV1Request& Lhs, const FPragma_Party_SendInviteV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_CreateV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_BroadcastParty Party;

};
PRAGMASDK_API bool operator==(const FPragma_Party_CreateV1Response& Lhs, const FPragma_Party_CreateV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_CreateV1Response& Lhs, const FPragma_Party_CreateV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_CreateV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtCreateRequest CreateRequestExt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Party_ExtPlayerJoinRequest PlayerJoinRequestExt;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameClientVersion;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> PreferredGameServerZones;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TMap<FString, int32> GameServerZoneToPing;

};
PRAGMASDK_API bool operator==(const FPragma_Party_CreateV1Request& Lhs, const FPragma_Party_CreateV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_CreateV1Request& Lhs, const FPragma_Party_CreateV1Request& Rhs);

