// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaDemoGrantsDto.h"

#include "PragmaPetDto.generated.h"

// Forward declarations.
struct FPragma_Inventory_PetUpdate;
struct FPragma_Inventory_Pet;
struct FPragma_Inventory_PetSpec;

//
// Source protos:
// shared/pet.proto
//


//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Inventory_PetBonus : uint8
{
	UNUSED = 0,
	XP_BONUS = 1,
	GOLD_BONUS = 2,
	LUCK_BONUS = 3,
};

//
// Messages.
//

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Inventory_PetUpdate
{
	GENERATED_BODY()

	UPROPERTY()
	int64 XpDelta{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GearToEquipInstanceId;

};
PRAGMASDK_API bool operator==(const FPragma_Inventory_PetUpdate& Lhs, const FPragma_Inventory_PetUpdate& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Inventory_PetUpdate& Lhs, const FPragma_Inventory_PetUpdate& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Inventory_Pet
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Inventory_PetBonus Bonus{static_cast<EPragma_Inventory_PetBonus>(0)};

	UPROPERTY()
	int64 BonusAmount{0};

	UPROPERTY()
	int64 Xp{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GearEquippedInstanceId;

};
PRAGMASDK_API bool operator==(const FPragma_Inventory_Pet& Lhs, const FPragma_Inventory_Pet& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Inventory_Pet& Lhs, const FPragma_Inventory_Pet& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Inventory_PetSpec
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<EPragma_Inventory_PetBonus> Bonuses;

	UPROPERTY()
	int64 BonusMin{0};

	UPROPERTY()
	int64 BonusMax{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Ext_DemoItemGrant> ItemGrants;

};
PRAGMASDK_API bool operator==(const FPragma_Inventory_PetSpec& Lhs, const FPragma_Inventory_PetSpec& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Inventory_PetSpec& Lhs, const FPragma_Inventory_PetSpec& Rhs);

