// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.h.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>
#pragma once
#include "PragmaResult.h"
#include "PragmaServerApi.h"
#include "Dto/PragmaPlayerDataServiceRpcDto.h"

#include "PragmaPlayerDataPartnerServiceRaw.generated.h"

struct FPragmaMessageMetadata;

UCLASS(Transient)
class PRAGMASDK_API UPragmaPlayerDataPartnerServiceRaw : public UPragmaServerApi
{
GENERATED_BODY()

public:

    void virtual OnInitialized() override;

    DECLARE_DELEGATE_TwoParams(FDoOperationPartnerV1Delegate, TPragmaResult<FPragma_PlayerData_DoOperationPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void DoOperationPartnerV1(const FPragma_PlayerData_DoOperationPartnerV1Request& Request, FDoOperationPartnerV1Delegate Delegate) const;
    virtual void DoOperationPartnerV1(const FPragma_PlayerData_DoOperationPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_PlayerData_DoOperationPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FGetPartnerV1Delegate, TPragmaResult<FPragma_PlayerData_GetPartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void GetPartnerV1(const FPragma_PlayerData_GetPartnerV1Request& Request, FGetPartnerV1Delegate Delegate) const;
    virtual void GetPartnerV1(const FPragma_PlayerData_GetPartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_PlayerData_GetPartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
    DECLARE_DELEGATE_TwoParams(FDeletePartnerV1Delegate, TPragmaResult<FPragma_PlayerData_DeletePartnerV1Response> /* Result */, const FPragmaMessageMetadata& /* Metadata */);
    virtual void DeletePartnerV1(const FPragma_PlayerData_DeletePartnerV1Request& Request, FDeletePartnerV1Delegate Delegate) const;
    virtual void DeletePartnerV1(const FPragma_PlayerData_DeletePartnerV1Request& Request, TUniqueFunction<void(TPragmaResult<FPragma_PlayerData_DeletePartnerV1Response>, const FPragmaMessageMetadata&)> Callback) const;
};

