// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaAccountCommonDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaPresenceExtDto.h"

#include "PragmaFriendCommonDto.generated.h"

// Forward declarations.
struct FPragma_Friend_Presence;
struct FPragma_Friend_FriendOverview;
struct FPragma_Friend_FriendListUpdates;
struct FPragma_Friend_Friend;
struct FPragma_Friend_FriendList;

//
// Source protos:
// pragma/friend/friendCommon.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_Presence
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameTitleId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString BasicPresence;

	UPROPERTY()
	int64 Version{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Presence_ExtRichPresence Ext;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_Presence& Lhs, const FPragma_Friend_Presence& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_Presence& Lhs, const FPragma_Friend_Presence& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_FriendOverview
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName DisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_FriendOverview& Lhs, const FPragma_Friend_FriendOverview& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_FriendOverview& Lhs, const FPragma_Friend_FriendOverview& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_FriendListUpdates
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_FriendOverview> FriendsAdded;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> FriendsRemoved;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_FriendOverview> ReceivedInvitesAdded;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> ReceivedInvitesRemoved;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_FriendOverview> SentInvitesAdded;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> SentInvitesRemoved;

	UPROPERTY()
	int64 Version{0};

};
PRAGMASDK_API bool operator==(const FPragma_Friend_FriendListUpdates& Lhs, const FPragma_Friend_FriendListUpdates& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_FriendListUpdates& Lhs, const FPragma_Friend_FriendListUpdates& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_Friend
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString PlayerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName DisplayName;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_Presence> Presences;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_Friend& Lhs, const FPragma_Friend_Friend& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_Friend& Lhs, const FPragma_Friend_Friend& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_FriendList
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_Friend> Friends;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_FriendOverview> SentInvites;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Friend_FriendOverview> ReceivedInvites;

	UPROPERTY()
	int64 Version{0};

};
PRAGMASDK_API bool operator==(const FPragma_Friend_FriendList& Lhs, const FPragma_Friend_FriendList& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_FriendList& Lhs, const FPragma_Friend_FriendList& Rhs);

