// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaMatchmakingServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaMatchmakingServiceRaw::OnInitialized()
{
    REGISTER_PRAGMA_GAME_EVENT(OnMatchmakingFailureV1, FPragma_Matchmaking_MatchmakingFailureV1Notification);
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaMatchmakingServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(LeaveMatchmakingV2, FPragma_Matchmaking_LeaveMatchmakingV2Request, FPragma_Matchmaking_LeaveMatchmakingV2Response, FLeaveMatchmakingV2Delegate);
IMPL_PRAGMA_METHOD(GetMatchmakingInfoV2, FPragma_Matchmaking_GetMatchmakingInfoV2Request, FPragma_Matchmaking_GetMatchmakingInfoV2Response, FGetMatchmakingInfoV2Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
