// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaPlayerDataTypesDto.h"

#include "PragmaPlayerDataExtDto.generated.h"

// Forward declarations.
struct FPragma_PlayerData_ExtComponent;

//
// Source protos:
// generated/pragma/playerdata/playerDataExt.proto
//


UENUM(BlueprintType, Category=Pragma)
enum class EPragma_PlayerData_ExtComponent_ComponentType : uint8
{
	Invalid,
	DemoComplexType,
	MyComponent,
	MyLiveDataComponent,
	NumberData,
	PlayerHiddenComponent,
	PlayerVisibleComponent,
	StringComponent,
	WalletComponent,
};

USTRUCT(BlueprintType, Category=Pragma)
struct PRAGMASDK_API FPragma_PlayerData_ExtComponent_Component
{
	GENERATED_BODY()

	FPragma_PlayerData_ExtComponent_Component();
	~FPragma_PlayerData_ExtComponent_Component();

	FPragma_PlayerData_ExtComponent_Component(const FPragma_PlayerData_ExtComponent_Component& Other);
	FPragma_PlayerData_ExtComponent_Component& operator=(const FPragma_PlayerData_ExtComponent_Component& Other);

    bool Equals(const FPragma_PlayerData_ExtComponent_Component& Other) const;

	void Reset();

	EPragma_PlayerData_ExtComponent_ComponentType OneOfType() const { return Type; }

	const FPragma_PlayerData_DemoComplexTypeProto& DemoComplexType() const;
	const FPragma_PlayerData_MyComponentProto& MyComponent() const;
	const FPragma_PlayerData_MyLiveDataComponentProto& MyLiveDataComponent() const;
	const FPragma_PlayerData_NumberDataProto& NumberData() const;
	const FPragma_PlayerData_PlayerHiddenComponentProto& PlayerHiddenComponent() const;
	const FPragma_PlayerData_PlayerVisibleComponentProto& PlayerVisibleComponent() const;
	const FPragma_PlayerData_StringComponentProto& StringComponent() const;
	const FPragma_PlayerData_WalletComponentProto& WalletComponent() const;

    void SetDemoComplexType(const FPragma_PlayerData_DemoComplexTypeProto& Value);
    void SetMyComponent(const FPragma_PlayerData_MyComponentProto& Value);
    void SetMyLiveDataComponent(const FPragma_PlayerData_MyLiveDataComponentProto& Value);
    void SetNumberData(const FPragma_PlayerData_NumberDataProto& Value);
    void SetPlayerHiddenComponent(const FPragma_PlayerData_PlayerHiddenComponentProto& Value);
    void SetPlayerVisibleComponent(const FPragma_PlayerData_PlayerVisibleComponentProto& Value);
    void SetStringComponent(const FPragma_PlayerData_StringComponentProto& Value);
    void SetWalletComponent(const FPragma_PlayerData_WalletComponentProto& Value);

	static bool SerializeIntoParentJson(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
	static bool DeserializeFromParentJson(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);

private:
	UPROPERTY()
	EPragma_PlayerData_ExtComponent_ComponentType Type { EPragma_PlayerData_ExtComponent_ComponentType::Invalid };

	union
	{
		TTypeCompatibleBytes<FPragma_PlayerData_DemoComplexTypeProto> DemoComplexType;
		TTypeCompatibleBytes<FPragma_PlayerData_MyComponentProto> MyComponent;
		TTypeCompatibleBytes<FPragma_PlayerData_MyLiveDataComponentProto> MyLiveDataComponent;
		TTypeCompatibleBytes<FPragma_PlayerData_NumberDataProto> NumberData;
		TTypeCompatibleBytes<FPragma_PlayerData_PlayerHiddenComponentProto> PlayerHiddenComponent;
		TTypeCompatibleBytes<FPragma_PlayerData_PlayerVisibleComponentProto> PlayerVisibleComponent;
		TTypeCompatibleBytes<FPragma_PlayerData_StringComponentProto> StringComponent;
		TTypeCompatibleBytes<FPragma_PlayerData_WalletComponentProto> WalletComponent;
	} Union{};
};
bool operator==(const FPragma_PlayerData_ExtComponent_Component& Lhs, const FPragma_PlayerData_ExtComponent_Component& Rhs);
bool operator!=(const FPragma_PlayerData_ExtComponent_Component& Lhs, const FPragma_PlayerData_ExtComponent_Component& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_PlayerData_ExtComponent
{
	GENERATED_BODY()

	UPROPERTY(Transient)
	FPragma_PlayerData_ExtComponent_Component Component;

    PRAGMASDK_API static bool AddonSerializer(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
    PRAGMASDK_API static bool AddonDeserializer(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);
};
PRAGMASDK_API bool operator==(const FPragma_PlayerData_ExtComponent& Lhs, const FPragma_PlayerData_ExtComponent& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_PlayerData_ExtComponent& Lhs, const FPragma_PlayerData_ExtComponent& Rhs);

