// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaInventoryServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaInventoryServiceRaw::OnInitialized()
{
    REGISTER_PRAGMA_GAME_EVENT(OnInventoryUpdatedV1, FPragma_Inventory_InventoryUpdatedV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnResetClientInventoryCacheVersionV1, FPragma_Inventory_ResetClientInventoryCacheVersionV1Notification);
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaInventoryServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(DeletePlayerInventoryV3, FPragma_Inventory_DeletePlayerInventoryV3Request, FPragma_Inventory_DeletePlayerInventoryV3Response, FDeletePlayerInventoryV3Delegate);
IMPL_PRAGMA_METHOD(StorePurchaseV4, FPragma_Inventory_StorePurchaseV4Request, FPragma_Inventory_StorePurchaseV4Response, FStorePurchaseV4Delegate);
IMPL_PRAGMA_METHOD(InitializeOrderV1, FPragma_Inventory_InitializeOrderV1Request, FPragma_Inventory_InitializeOrderV1Response, FInitializeOrderV1Delegate);
IMPL_PRAGMA_METHOD(FinalizeOrderV1, FPragma_Inventory_FinalizeOrderV1Request, FPragma_Inventory_FinalizeOrderV1Response, FFinalizeOrderV1Delegate);
IMPL_PRAGMA_METHOD(CancelOrderV1, FPragma_Inventory_CancelOrderV1Request, FPragma_Inventory_CancelOrderV1Response, FCancelOrderV1Delegate);
IMPL_PRAGMA_METHOD(FinalizeInProgressOrdersV1, FPragma_Inventory_FinalizeInProgressOrdersV1Request, FPragma_Inventory_FinalizeInProgressOrdersV1Response, FFinalizeInProgressOrdersV1Delegate);
IMPL_PRAGMA_METHOD(SyncEntitlementsV1, FPragma_Inventory_SyncEntitlementsV1Request, FPragma_Inventory_SyncEntitlementsV1Response, FSyncEntitlementsV1Delegate);
IMPL_PRAGMA_METHOD(UpdateItemV4, FPragma_Inventory_UpdateItemV4Request, FPragma_Inventory_UpdateItemV4Response, FUpdateItemV4Delegate);
IMPL_PRAGMA_METHOD(UpdateItemsV0, FPragma_Inventory_UpdateItemsV0Request, FPragma_Inventory_UpdateItemsV0Response, FUpdateItemsV0Delegate);
IMPL_PRAGMA_METHOD(CraftV1, FPragma_Inventory_CraftV1Request, FPragma_Inventory_CraftV1Response, FCraftV1Delegate);
IMPL_PRAGMA_METHOD(GetInventoryV2, FPragma_Inventory_GetInventoryV2Request, FPragma_Inventory_GetInventoryV2Response, FGetInventoryV2Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
