// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaOptionsDto.h"

#include "PragmaTelemetryRpcDto.generated.h"

// Forward declarations.
struct FPragma_Telemetry_EventsPartnerV1Response;
struct FPragma_Telemetry_EventPartnerV1Response;
struct FPragma_Telemetry_PlayerEventsV1Response;
struct FPragma_Telemetry_PlayerEventV1Response;
struct FPragma_Telemetry_TelemetryEvent;
struct FPragma_Telemetry_SourcedEvent;
struct FPragma_Telemetry_EventsPartnerV1Request;
struct FPragma_Telemetry_EventPartnerV1Request;
struct FPragma_Telemetry_PlayerEventsV1Request;
struct FPragma_Telemetry_PlayerEventV1Request;

//
// Source protos:
// pragma/telemetry/TelemetryRpc.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_EventsPartnerV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_EventsPartnerV1Response& Lhs, const FPragma_Telemetry_EventsPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_EventsPartnerV1Response& Lhs, const FPragma_Telemetry_EventsPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_EventPartnerV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_EventPartnerV1Response& Lhs, const FPragma_Telemetry_EventPartnerV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_EventPartnerV1Response& Lhs, const FPragma_Telemetry_EventPartnerV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_PlayerEventsV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_PlayerEventsV1Response& Lhs, const FPragma_Telemetry_PlayerEventsV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_PlayerEventsV1Response& Lhs, const FPragma_Telemetry_PlayerEventsV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_PlayerEventV1Response
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_PlayerEventV1Response& Lhs, const FPragma_Telemetry_PlayerEventV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_PlayerEventV1Response& Lhs, const FPragma_Telemetry_PlayerEventV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_TelemetryEvent
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Name;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Json;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_TelemetryEvent& Lhs, const FPragma_Telemetry_TelemetryEvent& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_TelemetryEvent& Lhs, const FPragma_Telemetry_TelemetryEvent& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_SourcedEvent
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SourceId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Telemetry_TelemetryEvent Event;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_SourcedEvent& Lhs, const FPragma_Telemetry_SourcedEvent& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_SourcedEvent& Lhs, const FPragma_Telemetry_SourcedEvent& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_EventsPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Telemetry_SourcedEvent> Events;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_EventsPartnerV1Request& Lhs, const FPragma_Telemetry_EventsPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_EventsPartnerV1Request& Lhs, const FPragma_Telemetry_EventsPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_EventPartnerV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SourceId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Telemetry_TelemetryEvent Event;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_EventPartnerV1Request& Lhs, const FPragma_Telemetry_EventPartnerV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_EventPartnerV1Request& Lhs, const FPragma_Telemetry_EventPartnerV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_PlayerEventsV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Telemetry_TelemetryEvent> Events;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_PlayerEventsV1Request& Lhs, const FPragma_Telemetry_PlayerEventsV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_PlayerEventsV1Request& Lhs, const FPragma_Telemetry_PlayerEventsV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Telemetry_PlayerEventV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Telemetry_TelemetryEvent Event;

};
PRAGMASDK_API bool operator==(const FPragma_Telemetry_PlayerEventV1Request& Lhs, const FPragma_Telemetry_PlayerEventV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Telemetry_PlayerEventV1Request& Lhs, const FPragma_Telemetry_PlayerEventV1Request& Rhs);

