// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaOptionsDto.h"

#include "PragmaPartyRpcExtDto.generated.h"

// Forward declarations.
struct FPragma_Party_ExtPrivatePlayer;
struct FPragma_Party_ExtBroadcastPlayer;
struct FPragma_Party_ExtBroadcastParty;
struct FPragma_Party_ExtUpdatePartyRequest;
struct FPragma_Party_ExtPlayerJoinRequest;
struct FPragma_Party_ExtCreateRequest;
struct FPragma_Party_ExtUpdatePartyPlayerRequest;

//
// Source protos:
// shared/partyRpcExt.proto
//


//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_Character : uint8
{
	CHARACTER_UNSPECIFIED = 0,
	KNIGHT = 1,
	MAGE = 2,
	ROGUE = 3,
};

//
// Messages.
//

//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_GameMode : uint8
{
	GAME_MODE_UNSPECIFIED = 0,
	EXPLORATION = 1,
	DUNGEON = 2,
	SOCIAL = 3,
};

//
// Messages.
//

//
// Enums.
//

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_MatchmakingStyle : uint8
{
	MATCHMAKING_STYLE_UNSPECIFIED = 0,
	STANDARD_MATCHMAKING = 1,
	DIRECT_TO_GAME = 2,
};

//
// Messages.
//

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtPrivatePlayer
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString VoipToken;

};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtPrivatePlayer& Lhs, const FPragma_Party_ExtPrivatePlayer& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtPrivatePlayer& Lhs, const FPragma_Party_ExtPrivatePlayer& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtBroadcastPlayer
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Party_Character DesiredCharacter{static_cast<EPragma_Party_Character>(0)};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SelectedCostumeCatalogId;

};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtBroadcastPlayer& Lhs, const FPragma_Party_ExtBroadcastPlayer& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtBroadcastPlayer& Lhs, const FPragma_Party_ExtBroadcastPlayer& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtBroadcastParty
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Party_GameMode GameMode{static_cast<EPragma_Party_GameMode>(0)};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	EPragma_Party_MatchmakingStyle MatchmakingStyle{static_cast<EPragma_Party_MatchmakingStyle>(0)};

	UPROPERTY()
	int64 MatchDurationInMillis{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString MatchmakingKey;

};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtBroadcastParty& Lhs, const FPragma_Party_ExtBroadcastParty& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtBroadcastParty& Lhs, const FPragma_Party_ExtBroadcastParty& Rhs);

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_ExtUpdatePartyRequest_UpdateType : uint8
{
	Invalid,
	NewGameMode,
	MatchmakingStyle,
	GameDurationInMillis,
	ShouldCauseMatchmakingException,
};

USTRUCT(BlueprintType, Category=Pragma)
struct PRAGMASDK_API FPragma_Party_ExtUpdatePartyRequest_Update
{
	GENERATED_BODY()

	FPragma_Party_ExtUpdatePartyRequest_Update();
	~FPragma_Party_ExtUpdatePartyRequest_Update();

	FPragma_Party_ExtUpdatePartyRequest_Update(const FPragma_Party_ExtUpdatePartyRequest_Update& Other);
	FPragma_Party_ExtUpdatePartyRequest_Update& operator=(const FPragma_Party_ExtUpdatePartyRequest_Update& Other);

    bool Equals(const FPragma_Party_ExtUpdatePartyRequest_Update& Other) const;

	void Reset();

	EPragma_Party_ExtUpdatePartyRequest_UpdateType OneOfType() const { return Type; }

	const EPragma_Party_GameMode& NewGameMode() const;
	const EPragma_Party_MatchmakingStyle& MatchmakingStyle() const;
	const int64& GameDurationInMillis() const;
	const bool& ShouldCauseMatchmakingException() const;

    void SetNewGameMode(const EPragma_Party_GameMode& Value);
    void SetMatchmakingStyle(const EPragma_Party_MatchmakingStyle& Value);
    void SetGameDurationInMillis(const int64& Value);
    void SetShouldCauseMatchmakingException(const bool& Value);

	static bool SerializeIntoParentJson(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
	static bool DeserializeFromParentJson(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);

private:
	UPROPERTY()
	EPragma_Party_ExtUpdatePartyRequest_UpdateType Type { EPragma_Party_ExtUpdatePartyRequest_UpdateType::Invalid };

	union
	{
		TTypeCompatibleBytes<EPragma_Party_GameMode> NewGameMode;
		TTypeCompatibleBytes<EPragma_Party_MatchmakingStyle> MatchmakingStyle;
		TTypeCompatibleBytes<int64> GameDurationInMillis;
		TTypeCompatibleBytes<bool> ShouldCauseMatchmakingException;
	} Union{};
};
bool operator==(const FPragma_Party_ExtUpdatePartyRequest_Update& Lhs, const FPragma_Party_ExtUpdatePartyRequest_Update& Rhs);
bool operator!=(const FPragma_Party_ExtUpdatePartyRequest_Update& Lhs, const FPragma_Party_ExtUpdatePartyRequest_Update& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtUpdatePartyRequest
{
	GENERATED_BODY()

	UPROPERTY(Transient)
	FPragma_Party_ExtUpdatePartyRequest_Update Update;

    PRAGMASDK_API static bool AddonSerializer(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
    PRAGMASDK_API static bool AddonDeserializer(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);
};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtUpdatePartyRequest& Lhs, const FPragma_Party_ExtUpdatePartyRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtUpdatePartyRequest& Lhs, const FPragma_Party_ExtUpdatePartyRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtPlayerJoinRequest
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtPlayerJoinRequest& Lhs, const FPragma_Party_ExtPlayerJoinRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtPlayerJoinRequest& Lhs, const FPragma_Party_ExtPlayerJoinRequest& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtCreateRequest
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString MatchmakingKey;

};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtCreateRequest& Lhs, const FPragma_Party_ExtCreateRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtCreateRequest& Lhs, const FPragma_Party_ExtCreateRequest& Rhs);

UENUM(BlueprintType, Category=Pragma)
enum class EPragma_Party_ExtUpdatePartyPlayerRequest_UpdateType : uint8
{
	Invalid,
	NewCharacterSelection,
	NewCostumeCatalogId,
};

USTRUCT(BlueprintType, Category=Pragma)
struct PRAGMASDK_API FPragma_Party_ExtUpdatePartyPlayerRequest_Update
{
	GENERATED_BODY()

	FPragma_Party_ExtUpdatePartyPlayerRequest_Update();
	~FPragma_Party_ExtUpdatePartyPlayerRequest_Update();

	FPragma_Party_ExtUpdatePartyPlayerRequest_Update(const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Other);
	FPragma_Party_ExtUpdatePartyPlayerRequest_Update& operator=(const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Other);

    bool Equals(const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Other) const;

	void Reset();

	EPragma_Party_ExtUpdatePartyPlayerRequest_UpdateType OneOfType() const { return Type; }

	const EPragma_Party_Character& NewCharacterSelection() const;
	const FString& NewCostumeCatalogId() const;

    void SetNewCharacterSelection(const EPragma_Party_Character& Value);
    void SetNewCostumeCatalogId(const FString& Value);

	static bool SerializeIntoParentJson(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
	static bool DeserializeFromParentJson(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);

private:
	UPROPERTY()
	EPragma_Party_ExtUpdatePartyPlayerRequest_UpdateType Type { EPragma_Party_ExtUpdatePartyPlayerRequest_UpdateType::Invalid };

	union
	{
		TTypeCompatibleBytes<EPragma_Party_Character> NewCharacterSelection;
		TTypeCompatibleBytes<FString> NewCostumeCatalogId;
	} Union{};
};
bool operator==(const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Lhs, const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Rhs);
bool operator!=(const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Lhs, const FPragma_Party_ExtUpdatePartyPlayerRequest_Update& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Party_ExtUpdatePartyPlayerRequest
{
	GENERATED_BODY()

	UPROPERTY()
	int64 CurrentInventoryVersion{0};

	UPROPERTY(Transient)
	FPragma_Party_ExtUpdatePartyPlayerRequest_Update Update;

    PRAGMASDK_API static bool AddonSerializer(const void* Value, TSharedRef<FJsonObject>& OutJsonObj);
    PRAGMASDK_API static bool AddonDeserializer(const TSharedRef<FJsonObject>& JsonObj, void* OutValue);
};
PRAGMASDK_API bool operator==(const FPragma_Party_ExtUpdatePartyPlayerRequest& Lhs, const FPragma_Party_ExtUpdatePartyPlayerRequest& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Party_ExtUpdatePartyPlayerRequest& Lhs, const FPragma_Party_ExtUpdatePartyPlayerRequest& Rhs);

