// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaDataRightsPartnerServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaDataRightsPartnerServiceRaw::OnInitialized()
{
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_SOCIAL_METHOD(UPragmaDataRightsPartnerServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(GetRequestsPartnerV1, FPragma_DataRights_GetRequestsPartnerV1Request, FPragma_DataRights_GetRequestsPartnerV1Response, FGetRequestsPartnerV1Delegate);
IMPL_PRAGMA_METHOD(SubmitRequestPartnerV1, FPragma_DataRights_SubmitRequestPartnerV1Request, FPragma_DataRights_SubmitRequestPartnerV1Response, FSubmitRequestPartnerV1Delegate);
IMPL_PRAGMA_METHOD(GetPersonalDataPackagePartnerV1, FPragma_DataRights_GetPersonalDataPackagePartnerV1Request, FPragma_DataRights_GetPersonalDataPackagePartnerV1Response, FGetPersonalDataPackagePartnerV1Delegate);
IMPL_PRAGMA_METHOD(GenerateDownloadUrlAndTokenPartnerV1, FPragma_DataRights_GenerateDownloadUrlAndTokenPartnerV1Request, FPragma_DataRights_GenerateDownloadUrlAndTokenPartnerV1Response, FGenerateDownloadUrlAndTokenPartnerV1Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
