// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/BackendTypes.mustache
// </auto-generated>
#pragma once

#include "PragmaBackendTypeData.h"
#include "Dto/PragmaEchoRpcDto.h"
#include "Dto/PragmaDelayedRpcDto.h"
#include "Dto/PragmaFriendRpcDto.h"
#include "Dto/PragmaGameInstanceRpcDto.h"
#include "Dto/PragmaPartyRpcDto.h"
#include "Dto/PragmaPaymentRpcDto.h"
#include "Dto/PragmaGameManagementRpcDto.h"
#include "Dto/PragmaPlayerDataServiceRpcDto.h"
#include "Dto/PragmaMatchmakingRpcDto.h"
#include "Dto/PragmaInventoryRpcDto.h"
#include "Dto/PragmaGameDataRpcDto.h"
#include "Dto/PragmaMatchCapacityRpcDto.h"
#include "Dto/PragmaDataRightsRpcDto.h"
#include "Dto/PragmaTelemetryRpcDto.h"
#include "Dto/PragmaAccountRpcDto.h"
#include "Dto/PragmaFleetRpcDto.h"
#include "Dto/PragmaPlayerSessionRpcDto.h"
#include "Dto/PragmaPartnerSessionRpcDto.h"

namespace PragmaGeneratedTypes
{
static const TArray<FPragmaBackendTypeData>& Get()
{
	static TArray<FPragmaBackendTypeData> Value =
	{
		FPragmaBackendTypeData{
			FPragma_Account_AddAccountTagsPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.AddAccountTagsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_AddAccountTagsPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.AddAccountTagsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_AddAccountToPlayerGroupPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.AddAccountToPlayerGroupPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_AddAccountToPlayerGroupPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.AddAccountToPlayerGroupPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_DeleteAccountPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.DeleteAccountPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_DeleteAccountPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.DeleteAccountPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetAccountTagsPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.GetAccountTagsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetAccountTagsPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.GetAccountTagsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetAccountV1Request::StaticStruct(),
			TEXT("AccountRpc.GetAccountV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetAccountV1Response::StaticStruct(),
			TEXT("AccountRpc.GetAccountV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Request::StaticStruct(),
			TEXT("AccountRpc.GetDisplayNameForPlayerIdPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetDisplayNameForPlayerIdPartnerV2Response::StaticStruct(),
			TEXT("AccountRpc.GetDisplayNameForPlayerIdPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Request::StaticStruct(),
			TEXT("AccountRpc.GetDisplayNameForPragmaPlayerIdV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetDisplayNameForPragmaPlayerIdV1Response::StaticStruct(),
			TEXT("AccountRpc.GetDisplayNameForPragmaPlayerIdV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPlayerIdentitiesPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.GetPlayerIdentitiesPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPlayerIdentitiesPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.GetPlayerIdentitiesPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaAccountOverviewsPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.GetPragmaAccountOverviewsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaAccountOverviewsPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.GetPragmaAccountOverviewsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Request::StaticStruct(),
			TEXT("AccountRpc.GetPragmaPlayerIdForDisplayNameV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaPlayerIdForDisplayNameV1Response::StaticStruct(),
			TEXT("AccountRpc.GetPragmaPlayerIdForDisplayNameV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Request::StaticStruct(),
			TEXT("AccountRpc.GetPragmaPlayerIdsForProviderIdsV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetPragmaPlayerIdsForProviderIdsV2Response::StaticStruct(),
			TEXT("AccountRpc.GetPragmaPlayerIdsForProviderIdsV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetSocialIdentitiesPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.GetSocialIdentitiesPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_GetSocialIdentitiesPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.GetSocialIdentitiesPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_LinkIdentityProviderAccountPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.LinkIdentityProviderAccountPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_LinkIdentityProviderAccountPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.LinkIdentityProviderAccountPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_LinkIdentityProviderAccountV2Request::StaticStruct(),
			TEXT("AccountRpc.LinkIdentityProviderAccountV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_LinkIdentityProviderAccountV2Response::StaticStruct(),
			TEXT("AccountRpc.LinkIdentityProviderAccountV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RefreshTokensV1Request::StaticStruct(),
			TEXT("AccountRpc.RefreshTokensV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RefreshTokensV1Response::StaticStruct(),
			TEXT("AccountRpc.RefreshTokensV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.RemoveAccountFromPlayerGroupPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RemoveAccountFromPlayerGroupPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.RemoveAccountFromPlayerGroupPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RemoveAccountTagsPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.RemoveAccountTagsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_RemoveAccountTagsPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.RemoveAccountTagsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.UnlinkIdentityProviderAccountPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UnlinkIdentityProviderAccountPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.UnlinkIdentityProviderAccountPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UpdateDisplayNameV1Request::StaticStruct(),
			TEXT("AccountRpc.UpdateDisplayNameV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UpdateDisplayNameV1Response::StaticStruct(),
			TEXT("AccountRpc.UpdateDisplayNameV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UpdateEmailV1Request::StaticStruct(),
			TEXT("AccountRpc.UpdateEmailV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_UpdateEmailV1Response::StaticStruct(),
			TEXT("AccountRpc.UpdateEmailV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_ViewSocialIdentityPartnerV2Request::StaticStruct(),
			TEXT("AccountRpc.ViewSocialIdentityPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_ViewSocialIdentityPartnerV2Response::StaticStruct(),
			TEXT("AccountRpc.ViewSocialIdentityPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_ViewTagsPartnerV1Request::StaticStruct(),
			TEXT("AccountRpc.ViewTagsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Account_ViewTagsPartnerV1Response::StaticStruct(),
			TEXT("AccountRpc.ViewTagsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GenerateDownloadUrlAndTokenPartnerV1Request::StaticStruct(),
			TEXT("DataRightsRpc.GenerateDownloadUrlAndTokenPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GenerateDownloadUrlAndTokenPartnerV1Response::StaticStruct(),
			TEXT("DataRightsRpc.GenerateDownloadUrlAndTokenPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GetPersonalDataPackagePartnerV1Request::StaticStruct(),
			TEXT("DataRightsRpc.GetPersonalDataPackagePartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GetPersonalDataPackagePartnerV1Response::StaticStruct(),
			TEXT("DataRightsRpc.GetPersonalDataPackagePartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GetRequestsPartnerV1Request::StaticStruct(),
			TEXT("DataRightsRpc.GetRequestsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_GetRequestsPartnerV1Response::StaticStruct(),
			TEXT("DataRightsRpc.GetRequestsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_SubmitRequestPartnerV1Request::StaticStruct(),
			TEXT("DataRightsRpc.SubmitRequestPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_SubmitRequestPartnerV1Response::StaticStruct(),
			TEXT("DataRightsRpc.SubmitRequestPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_SubmitRequestV1Request::StaticStruct(),
			TEXT("DataRightsRpc.SubmitRequestV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_DataRights_SubmitRequestV1Response::StaticStruct(),
			TEXT("DataRightsRpc.SubmitRequestV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Delayed_DelayedV1Request::StaticStruct(),
			TEXT("DelayedRpc.DelayedV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Delayed_DelayedV1Response::StaticStruct(),
			TEXT("DelayedRpc.DelayedV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Echo_EchoV1Request::StaticStruct(),
			TEXT("EchoRpc.EchoV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Echo_EchoV1Response::StaticStruct(),
			TEXT("EchoRpc.EchoV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Fleet_ReportCapacityV1Request::StaticStruct(),
			TEXT("FleetRpc.ReportCapacityV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Fleet_ReportCapacityV1Response::StaticStruct(),
			TEXT("FleetRpc.ReportCapacityV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_FriendListUpdateV1Notification::StaticStruct(),
			TEXT("FriendRpc.FriendListUpdateV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_FriendUpdateV1Notification::StaticStruct(),
			TEXT("FriendRpc.FriendUpdateV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_GetFriendListV1Request::StaticStruct(),
			TEXT("FriendRpc.GetFriendListV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_GetFriendListV1Response::StaticStruct(),
			TEXT("FriendRpc.GetFriendListV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_IntegrationTestDeleteFriendDataV1Request::StaticStruct(),
			TEXT("FriendRpc.IntegrationTestDeleteFriendDataV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_IntegrationTestDeleteFriendDataV1Response::StaticStruct(),
			TEXT("FriendRpc.IntegrationTestDeleteFriendDataV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_PresenceUpdateV1Notification::StaticStruct(),
			TEXT("FriendRpc.PresenceUpdateV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_RemoveFriendV1Request::StaticStruct(),
			TEXT("FriendRpc.RemoveFriendV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_RemoveFriendV1Response::StaticStruct(),
			TEXT("FriendRpc.RemoveFriendV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_RespondToFriendInviteV1Request::StaticStruct(),
			TEXT("FriendRpc.RespondToFriendInviteV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_RespondToFriendInviteV1Response::StaticStruct(),
			TEXT("FriendRpc.RespondToFriendInviteV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SendFriendInviteBySocialIdV1Request::StaticStruct(),
			TEXT("FriendRpc.SendFriendInviteBySocialIdV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SendFriendInviteBySocialIdV1Response::StaticStruct(),
			TEXT("FriendRpc.SendFriendInviteBySocialIdV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SendFriendInviteV1Request::StaticStruct(),
			TEXT("FriendRpc.SendFriendInviteV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SendFriendInviteV1Response::StaticStruct(),
			TEXT("FriendRpc.SendFriendInviteV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SetPresenceV1Request::StaticStruct(),
			TEXT("FriendRpc.SetPresenceV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Friend_SetPresenceV1Response::StaticStruct(),
			TEXT("FriendRpc.SetPresenceV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameData_GetLoginDataV3Request::StaticStruct(),
			TEXT("GameDataRpc.GetLoginDataV3Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameData_GetLoginDataV3Response::StaticStruct(),
			TEXT("GameDataRpc.GetLoginDataV3Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_AddPlayersV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.AddPlayersV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_AddedToGameV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.AddedToGameV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_ConnectMorePlayersV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.ConnectMorePlayersV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_ConnectMorePlayersV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.ConnectMorePlayersV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_ConnectPlayersV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.ConnectPlayersV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_ConnectPlayersV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.ConnectPlayersV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_DeclineReconnectV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.DeclineReconnectV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_DeclineReconnectV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.DeclineReconnectV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_EndGameV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.EndGameV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_EndGameV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.EndGameV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_EnterMatchmakingV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.EnterMatchmakingV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_EnterMatchmakingV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.EnterMatchmakingV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameEndedV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameEndedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameInstanceEnteredMatchmakingV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameInstanceEnteredMatchmakingV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameInstanceLeftMatchmakingV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameInstanceLeftMatchmakingV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameInstanceReconnectV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameInstanceReconnectV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameInstanceStartFailureV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameInstanceStartFailureV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameInstanceTerminationV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.GameInstanceTerminationV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameKeepAliveV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.GameKeepAliveV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GameKeepAliveV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.GameKeepAliveV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GetGameStartDataV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.GetGameStartDataV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GetGameStartDataV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.GetGameStartDataV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GetHostConnectionDetailsV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.GetHostConnectionDetailsV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_GetHostConnectionDetailsV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.GetHostConnectionDetailsV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_HostConnectionDetailsV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.HostConnectionDetailsV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_LeaveMatchmakingV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.LeaveMatchmakingV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_LeaveMatchmakingV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.LeaveMatchmakingV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_PlayerDeclinedReconnectV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.PlayerDeclinedReconnectV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_RemovePlayersV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.RemovePlayersV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_RemovePlayersV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.RemovePlayersV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_RemovedFromGameV1Notification::StaticStruct(),
			TEXT("GameInstanceRpc.RemovedFromGameV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_UpdateGameInstanceV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.UpdateGameInstanceV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_UpdateGameInstanceV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.UpdateGameInstanceV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_VerifyPlayerPartnerV1Request::StaticStruct(),
			TEXT("GameInstanceRpc.VerifyPlayerPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameInstance_VerifyPlayerPartnerV1Response::StaticStruct(),
			TEXT("GameInstanceRpc.VerifyPlayerPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameManagement_GetAllLimitedAccessEventsPartnerV1Request::StaticStruct(),
			TEXT("GameManagementRpc.GetAllLimitedAccessEventsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_GameManagement_GetAllLimitedAccessEventsPartnerV1Response::StaticStruct(),
			TEXT("GameManagementRpc.GetAllLimitedAccessEventsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_ApplyInventoryOperationsPartnerV1Request::StaticStruct(),
			TEXT("InventoryRpc.ApplyInventoryOperationsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_ApplyInventoryOperationsPartnerV1Response::StaticStruct(),
			TEXT("InventoryRpc.ApplyInventoryOperationsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_CancelOrderV1Request::StaticStruct(),
			TEXT("InventoryRpc.CancelOrderV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_CancelOrderV1Response::StaticStruct(),
			TEXT("InventoryRpc.CancelOrderV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Request::StaticStruct(),
			TEXT("InventoryRpc.ClearPlayerInventoryCachePartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Response::StaticStruct(),
			TEXT("InventoryRpc.ClearPlayerInventoryCachePartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_CraftV1Request::StaticStruct(),
			TEXT("InventoryRpc.CraftV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_CraftV1Response::StaticStruct(),
			TEXT("InventoryRpc.CraftV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DeletePlayerInventoryPartnerV1Request::StaticStruct(),
			TEXT("InventoryRpc.DeletePlayerInventoryPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DeletePlayerInventoryPartnerV1Response::StaticStruct(),
			TEXT("InventoryRpc.DeletePlayerInventoryPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DeletePlayerInventoryV3Request::StaticStruct(),
			TEXT("InventoryRpc.DeletePlayerInventoryV3Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DeletePlayerInventoryV3Response::StaticStruct(),
			TEXT("InventoryRpc.DeletePlayerInventoryV3Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DestroyItemsPartnerV2Request::StaticStruct(),
			TEXT("InventoryRpc.DestroyItemsPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_DestroyItemsPartnerV2Response::StaticStruct(),
			TEXT("InventoryRpc.DestroyItemsPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_FinalizeInProgressOrdersV1Request::StaticStruct(),
			TEXT("InventoryRpc.FinalizeInProgressOrdersV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_FinalizeInProgressOrdersV1Response::StaticStruct(),
			TEXT("InventoryRpc.FinalizeInProgressOrdersV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_FinalizeOrderV1Request::StaticStruct(),
			TEXT("InventoryRpc.FinalizeOrderV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_FinalizeOrderV1Response::StaticStruct(),
			TEXT("InventoryRpc.FinalizeOrderV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetInventoryPartnerV2Request::StaticStruct(),
			TEXT("InventoryRpc.GetInventoryPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetInventoryPartnerV2Response::StaticStruct(),
			TEXT("InventoryRpc.GetInventoryPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetInventoryV2Request::StaticStruct(),
			TEXT("InventoryRpc.GetInventoryV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetInventoryV2Response::StaticStruct(),
			TEXT("InventoryRpc.GetInventoryV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Request::StaticStruct(),
			TEXT("InventoryRpc.GetProviderEntitlementHistoryPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Response::StaticStruct(),
			TEXT("InventoryRpc.GetProviderEntitlementHistoryPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GrantItemsPartnerV2Request::StaticStruct(),
			TEXT("InventoryRpc.GrantItemsPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_GrantItemsPartnerV2Response::StaticStruct(),
			TEXT("InventoryRpc.GrantItemsPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_InitializeOrderV1Request::StaticStruct(),
			TEXT("InventoryRpc.InitializeOrderV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_InitializeOrderV1Response::StaticStruct(),
			TEXT("InventoryRpc.InitializeOrderV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_InventoryUpdatedV1Notification::StaticStruct(),
			TEXT("InventoryRpc.InventoryUpdatedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_ResetClientInventoryCacheVersionV1Notification::StaticStruct(),
			TEXT("InventoryRpc.ResetClientInventoryCacheVersionV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SimulateRewardsV2Request::StaticStruct(),
			TEXT("InventoryRpc.SimulateRewardsV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SimulateRewardsV2Response::StaticStruct(),
			TEXT("InventoryRpc.SimulateRewardsV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_StorePurchaseV4Request::StaticStruct(),
			TEXT("InventoryRpc.StorePurchaseV4Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_StorePurchaseV4Response::StaticStruct(),
			TEXT("InventoryRpc.StorePurchaseV4Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SyncEntitlementsPartnerV1Request::StaticStruct(),
			TEXT("InventoryRpc.SyncEntitlementsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SyncEntitlementsPartnerV1Response::StaticStruct(),
			TEXT("InventoryRpc.SyncEntitlementsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SyncEntitlementsV1Request::StaticStruct(),
			TEXT("InventoryRpc.SyncEntitlementsV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_SyncEntitlementsV1Response::StaticStruct(),
			TEXT("InventoryRpc.SyncEntitlementsV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemV4Request::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemV4Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemV4Response::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemV4Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemsPartnerV2Request::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemsPartnerV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemsPartnerV2Response::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemsPartnerV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemsV0Request::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemsV0Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Inventory_UpdateItemsV0Response::StaticStruct(),
			TEXT("InventoryRpc.UpdateItemsV0Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_MatchCapacity_ReportCapacityV2Request::StaticStruct(),
			TEXT("MatchCapacityRpc.ReportCapacityV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_MatchCapacity_ReportCapacityV2Response::StaticStruct(),
			TEXT("MatchCapacityRpc.ReportCapacityV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Matchmaking_GetMatchmakingInfoV2Request::StaticStruct(),
			TEXT("MatchmakingRpc.GetMatchmakingInfoV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Matchmaking_GetMatchmakingInfoV2Response::StaticStruct(),
			TEXT("MatchmakingRpc.GetMatchmakingInfoV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Matchmaking_LeaveMatchmakingV2Request::StaticStruct(),
			TEXT("MatchmakingRpc.LeaveMatchmakingV2Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Matchmaking_LeaveMatchmakingV2Response::StaticStruct(),
			TEXT("MatchmakingRpc.LeaveMatchmakingV2Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Matchmaking_MatchmakingFailureV1Notification::StaticStruct(),
			TEXT("MatchmakingRpc.MatchmakingFailureV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_HeartbeatPartnerV1Request::StaticStruct(),
			TEXT("PartnerSessionRpc.HeartbeatPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_HeartbeatPartnerV1Response::StaticStruct(),
			TEXT("PartnerSessionRpc.HeartbeatPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_PartnerSessionTerminatedV1Notification::StaticStruct(),
			TEXT("PartnerSessionRpc.PartnerSessionTerminatedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_AssignPartyLeaderV1Request::StaticStruct(),
			TEXT("PartyRpc.AssignPartyLeaderV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_AssignPartyLeaderV1Response::StaticStruct(),
			TEXT("PartyRpc.AssignPartyLeaderV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_CreateV1Request::StaticStruct(),
			TEXT("PartyRpc.CreateV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_CreateV1Response::StaticStruct(),
			TEXT("PartyRpc.CreateV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_DevelopmentOverrideGameServerVersionV1Request::StaticStruct(),
			TEXT("PartyRpc.DevelopmentOverrideGameServerVersionV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_DevelopmentOverrideGameServerVersionV1Response::StaticStruct(),
			TEXT("PartyRpc.DevelopmentOverrideGameServerVersionV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_EnterMatchmakingV1Request::StaticStruct(),
			TEXT("PartyRpc.EnterMatchmakingV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_EnterMatchmakingV1Response::StaticStruct(),
			TEXT("PartyRpc.EnterMatchmakingV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_GameClientNotSupportedV1Notification::StaticStruct(),
			TEXT("PartyRpc.GameClientNotSupportedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_InviteReceivedV1Notification::StaticStruct(),
			TEXT("PartyRpc.InviteReceivedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_InviteResponseV1Notification::StaticStruct(),
			TEXT("PartyRpc.InviteResponseV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_JoinWithInviteCodeV1Request::StaticStruct(),
			TEXT("PartyRpc.JoinWithInviteCodeV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_JoinWithInviteCodeV1Response::StaticStruct(),
			TEXT("PartyRpc.JoinWithInviteCodeV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_JoinWithPartyIdV1Request::StaticStruct(),
			TEXT("PartyRpc.JoinWithPartyIdV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_JoinWithPartyIdV1Response::StaticStruct(),
			TEXT("PartyRpc.JoinWithPartyIdV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_KickV1Request::StaticStruct(),
			TEXT("PartyRpc.KickV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_KickV1Response::StaticStruct(),
			TEXT("PartyRpc.KickV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_LeaveV1Request::StaticStruct(),
			TEXT("PartyRpc.LeaveV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_LeaveV1Response::StaticStruct(),
			TEXT("PartyRpc.LeaveV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_PartyClientVersionMismatchV1Notification::StaticStruct(),
			TEXT("PartyRpc.PartyClientVersionMismatchV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_PartyDetailsV1Notification::StaticStruct(),
			TEXT("PartyRpc.PartyDetailsV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_RemovedV1Notification::StaticStruct(),
			TEXT("PartyRpc.RemovedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_RespondToInviteV1Request::StaticStruct(),
			TEXT("PartyRpc.RespondToInviteV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_RespondToInviteV1Response::StaticStruct(),
			TEXT("PartyRpc.RespondToInviteV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SendInviteV1Request::StaticStruct(),
			TEXT("PartyRpc.SendInviteV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SendInviteV1Response::StaticStruct(),
			TEXT("PartyRpc.SendInviteV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetGameServerZoneToPingV1Request::StaticStruct(),
			TEXT("PartyRpc.SetGameServerZoneToPingV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetGameServerZoneToPingV1Response::StaticStruct(),
			TEXT("PartyRpc.SetGameServerZoneToPingV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetPreferredGameServerZonesV1Request::StaticStruct(),
			TEXT("PartyRpc.SetPreferredGameServerZonesV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetPreferredGameServerZonesV1Response::StaticStruct(),
			TEXT("PartyRpc.SetPreferredGameServerZonesV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetReadyStateV1Request::StaticStruct(),
			TEXT("PartyRpc.SetReadyStateV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_SetReadyStateV1Response::StaticStruct(),
			TEXT("PartyRpc.SetReadyStateV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_UpdatePartyPlayerV1Request::StaticStruct(),
			TEXT("PartyRpc.UpdatePartyPlayerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_UpdatePartyPlayerV1Response::StaticStruct(),
			TEXT("PartyRpc.UpdatePartyPlayerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_UpdatePartyV1Request::StaticStruct(),
			TEXT("PartyRpc.UpdatePartyV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Party_UpdatePartyV1Response::StaticStruct(),
			TEXT("PartyRpc.UpdatePartyV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Payment_GetProductEntriesV1Request::StaticStruct(),
			TEXT("PaymentRpc.GetProductEntriesV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Payment_GetProductEntriesV1Response::StaticStruct(),
			TEXT("PaymentRpc.GetProductEntriesV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DeletePartnerV1Request::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DeletePartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DeletePartnerV1Response::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DeletePartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DoOperationPartnerV1Request::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DoOperationPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DoOperationPartnerV1Response::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DoOperationPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DoOperationV1Request::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DoOperationV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_DoOperationV1Response::StaticStruct(),
			TEXT("PlayerDataServiceRpc.DoOperationV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_GetPartnerV1Request::StaticStruct(),
			TEXT("PlayerDataServiceRpc.GetPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_GetPartnerV1Response::StaticStruct(),
			TEXT("PlayerDataServiceRpc.GetPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_GetV1Request::StaticStruct(),
			TEXT("PlayerDataServiceRpc.GetV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_GetV1Response::StaticStruct(),
			TEXT("PlayerDataServiceRpc.GetV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_PlayerData_PlayerDataUpdatedV1Notification::StaticStruct(),
			TEXT("PlayerDataServiceRpc.PlayerDataUpdatedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_HeartbeatV1Request::StaticStruct(),
			TEXT("PlayerSessionRpc.HeartbeatV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_HeartbeatV1Response::StaticStruct(),
			TEXT("PlayerSessionRpc.HeartbeatV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_RequestLogoutV1Request::StaticStruct(),
			TEXT("PlayerSessionRpc.RequestLogoutV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_RequestLogoutV1Response::StaticStruct(),
			TEXT("PlayerSessionRpc.RequestLogoutV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_SessionChangedV1Notification::StaticStruct(),
			TEXT("PlayerSessionRpc.SessionChangedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_SessionRefreshV1Request::StaticStruct(),
			TEXT("PlayerSessionRpc.SessionRefreshV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_SessionRefreshV1Response::StaticStruct(),
			TEXT("PlayerSessionRpc.SessionRefreshV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Session_SessionTerminatedV1Notification::StaticStruct(),
			TEXT("PlayerSessionRpc.SessionTerminatedV1Notification"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_EventPartnerV1Request::StaticStruct(),
			TEXT("TelemetryRpc.EventPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_EventPartnerV1Response::StaticStruct(),
			TEXT("TelemetryRpc.EventPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_EventsPartnerV1Request::StaticStruct(),
			TEXT("TelemetryRpc.EventsPartnerV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_EventsPartnerV1Response::StaticStruct(),
			TEXT("TelemetryRpc.EventsPartnerV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_PlayerEventV1Request::StaticStruct(),
			TEXT("TelemetryRpc.PlayerEventV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_PlayerEventV1Response::StaticStruct(),
			TEXT("TelemetryRpc.PlayerEventV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_PlayerEventsV1Request::StaticStruct(),
			TEXT("TelemetryRpc.PlayerEventsV1Request"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
		FPragmaBackendTypeData{
			FPragma_Telemetry_PlayerEventsV1Response::StaticStruct(),
			TEXT("TelemetryRpc.PlayerEventsV1Response"),
			-1 // Filled in at runtime from querying the backend types endpoint.
		},
	};
	return Value;
}
}
