// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaOptionsDto.h"

#include "PragmaXboxDto.generated.h"

// Forward declarations.
struct FPragma_Xbox_XboxEntitlement;

//
// Source protos:
// pragmaconfidential/xbox/xbox.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Xbox_XboxEntitlement
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString XboxProductId;

};
PRAGMASDK_API bool operator==(const FPragma_Xbox_XboxEntitlement& Lhs, const FPragma_Xbox_XboxEntitlement& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Xbox_XboxEntitlement& Lhs, const FPragma_Xbox_XboxEntitlement& Rhs);

