// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaPlayerDataServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaPlayerDataServiceRaw::OnInitialized()
{
    REGISTER_PRAGMA_GAME_EVENT(OnPlayerDataUpdatedV1, FPragma_PlayerData_PlayerDataUpdatedV1Notification);
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaPlayerDataServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(DoOperationV1, FPragma_PlayerData_DoOperationV1Request, FPragma_PlayerData_DoOperationV1Response, FDoOperationV1Delegate);
IMPL_PRAGMA_METHOD(GetV1, FPragma_PlayerData_GetV1Request, FPragma_PlayerData_GetV1Response, FGetV1Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
