// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaPartyServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaPartyServiceRaw::OnInitialized()
{
    REGISTER_PRAGMA_GAME_EVENT(OnPartyDetailsV1, FPragma_Party_PartyDetailsV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnInviteReceivedV1, FPragma_Party_InviteReceivedV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnInviteResponseV1, FPragma_Party_InviteResponseV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnGameClientNotSupportedV1, FPragma_Party_GameClientNotSupportedV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnPartyClientVersionMismatchV1, FPragma_Party_PartyClientVersionMismatchV1Notification);
    REGISTER_PRAGMA_GAME_EVENT(OnRemovedV1, FPragma_Party_RemovedV1Notification);
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaPartyServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(CreateV1, FPragma_Party_CreateV1Request, FPragma_Party_CreateV1Response, FCreateV1Delegate);
IMPL_PRAGMA_METHOD(SendInviteV1, FPragma_Party_SendInviteV1Request, FPragma_Party_SendInviteV1Response, FSendInviteV1Delegate);
IMPL_PRAGMA_METHOD(RespondToInviteV1, FPragma_Party_RespondToInviteV1Request, FPragma_Party_RespondToInviteV1Response, FRespondToInviteV1Delegate);
IMPL_PRAGMA_METHOD(JoinWithInviteCodeV1, FPragma_Party_JoinWithInviteCodeV1Request, FPragma_Party_JoinWithInviteCodeV1Response, FJoinWithInviteCodeV1Delegate);
IMPL_PRAGMA_METHOD(JoinWithPartyIdV1, FPragma_Party_JoinWithPartyIdV1Request, FPragma_Party_JoinWithPartyIdV1Response, FJoinWithPartyIdV1Delegate);
IMPL_PRAGMA_METHOD(AssignPartyLeaderV1, FPragma_Party_AssignPartyLeaderV1Request, FPragma_Party_AssignPartyLeaderV1Response, FAssignPartyLeaderV1Delegate);
IMPL_PRAGMA_METHOD(KickV1, FPragma_Party_KickV1Request, FPragma_Party_KickV1Response, FKickV1Delegate);
IMPL_PRAGMA_METHOD(LeaveV1, FPragma_Party_LeaveV1Request, FPragma_Party_LeaveV1Response, FLeaveV1Delegate);
IMPL_PRAGMA_METHOD(SetReadyStateV1, FPragma_Party_SetReadyStateV1Request, FPragma_Party_SetReadyStateV1Response, FSetReadyStateV1Delegate);
IMPL_PRAGMA_METHOD(SetPreferredGameServerZonesV1, FPragma_Party_SetPreferredGameServerZonesV1Request, FPragma_Party_SetPreferredGameServerZonesV1Response, FSetPreferredGameServerZonesV1Delegate);
IMPL_PRAGMA_METHOD(SetGameServerZoneToPingV1, FPragma_Party_SetGameServerZoneToPingV1Request, FPragma_Party_SetGameServerZoneToPingV1Response, FSetGameServerZoneToPingV1Delegate);
IMPL_PRAGMA_METHOD(UpdatePartyPlayerV1, FPragma_Party_UpdatePartyPlayerV1Request, FPragma_Party_UpdatePartyPlayerV1Response, FUpdatePartyPlayerV1Delegate);
IMPL_PRAGMA_METHOD(UpdatePartyV1, FPragma_Party_UpdatePartyV1Request, FPragma_Party_UpdatePartyV1Response, FUpdatePartyV1Delegate);
IMPL_PRAGMA_METHOD(DevelopmentOverrideGameServerVersionV1, FPragma_Party_DevelopmentOverrideGameServerVersionV1Request, FPragma_Party_DevelopmentOverrideGameServerVersionV1Response, FDevelopmentOverrideGameServerVersionV1Delegate);
IMPL_PRAGMA_METHOD(EnterMatchmakingV1, FPragma_Party_EnterMatchmakingV1Request, FPragma_Party_EnterMatchmakingV1Response, FEnterMatchmakingV1Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
