// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.cpp.mustache
// </auto-generated>

#include "PragmaFleetRpcDto.h"
#include "CoreMinimal.h"
#include "PragmaJson.h"



bool operator==(const FPragma_Fleet_ReportCapacityV1Response& Lhs, const FPragma_Fleet_ReportCapacityV1Response& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.NextHeartbeatPeriodMillis == Rhs.NextHeartbeatPeriodMillis
			&& Lhs.GameInstanceIds == Rhs.GameInstanceIds
;
}
bool operator!=(const FPragma_Fleet_ReportCapacityV1Response& Lhs, const FPragma_Fleet_ReportCapacityV1Response& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_Fleet_ReportCapacityV1Request& Lhs, const FPragma_Fleet_ReportCapacityV1Request& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.ServerId == Rhs.ServerId
			&& Lhs.ServerPoolId == Rhs.ServerPoolId
			&& Lhs.TotalCapacity == Rhs.TotalCapacity
			&& Lhs.UsedCapacity == Rhs.UsedCapacity
;
}
bool operator!=(const FPragma_Fleet_ReportCapacityV1Request& Lhs, const FPragma_Fleet_ReportCapacityV1Request& Rhs)
{
	return !(Lhs == Rhs);
}
