// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/RawService.cpp.mustache
//
//      NOTE:
//      You can suppress Raw API files from being generated for a particular service by adding the
//      following to the pom invocation of the protoc-maven-plugin:
//      <protocPlugin>
//          <!-- other config -->
//          <args>
//              <arg>--noCodegenServices=MyServiceName</arg>
//          </args>
//      </protocPlugin>
// </auto-generated>

#include "Dto/PragmaInventoryPartnerServiceRaw.h"

#include "PragmaServiceImplMacros.h"
#include "PragmaProtocol.h"
#include "PragmaMessageMetadata.h"

void UPragmaInventoryPartnerServiceRaw::OnInitialized()
{
}

#define IMPL_PRAGMA_METHOD(FunctionName, RequestType, ResponseType, DelegateType) \
IMPL_PRAGMA_GAME_METHOD(UPragmaInventoryPartnerServiceRaw, FunctionName, RequestType, ResponseType, DelegateType)

IMPL_PRAGMA_METHOD(DeletePlayerInventoryPartnerV1, FPragma_Inventory_DeletePlayerInventoryPartnerV1Request, FPragma_Inventory_DeletePlayerInventoryPartnerV1Response, FDeletePlayerInventoryPartnerV1Delegate);
IMPL_PRAGMA_METHOD(ClearPlayerInventoryCachePartnerV1, FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Request, FPragma_Inventory_ClearPlayerInventoryCachePartnerV1Response, FClearPlayerInventoryCachePartnerV1Delegate);
IMPL_PRAGMA_METHOD(SyncEntitlementsPartnerV1, FPragma_Inventory_SyncEntitlementsPartnerV1Request, FPragma_Inventory_SyncEntitlementsPartnerV1Response, FSyncEntitlementsPartnerV1Delegate);
IMPL_PRAGMA_METHOD(UpdateItemsPartnerV2, FPragma_Inventory_UpdateItemsPartnerV2Request, FPragma_Inventory_UpdateItemsPartnerV2Response, FUpdateItemsPartnerV2Delegate);
IMPL_PRAGMA_METHOD(SimulateRewardsV2, FPragma_Inventory_SimulateRewardsV2Request, FPragma_Inventory_SimulateRewardsV2Response, FSimulateRewardsV2Delegate);
IMPL_PRAGMA_METHOD(GrantItemsPartnerV2, FPragma_Inventory_GrantItemsPartnerV2Request, FPragma_Inventory_GrantItemsPartnerV2Response, FGrantItemsPartnerV2Delegate);
IMPL_PRAGMA_METHOD(DestroyItemsPartnerV2, FPragma_Inventory_DestroyItemsPartnerV2Request, FPragma_Inventory_DestroyItemsPartnerV2Response, FDestroyItemsPartnerV2Delegate);
IMPL_PRAGMA_METHOD(GetInventoryPartnerV2, FPragma_Inventory_GetInventoryPartnerV2Request, FPragma_Inventory_GetInventoryPartnerV2Response, FGetInventoryPartnerV2Delegate);
IMPL_PRAGMA_METHOD(ApplyInventoryOperationsPartnerV1, FPragma_Inventory_ApplyInventoryOperationsPartnerV1Request, FPragma_Inventory_ApplyInventoryOperationsPartnerV1Response, FApplyInventoryOperationsPartnerV1Delegate);
IMPL_PRAGMA_METHOD(GetProviderEntitlementHistoryPartnerV1, FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Request, FPragma_Inventory_GetProviderEntitlementHistoryPartnerV1Response, FGetProviderEntitlementHistoryPartnerV1Delegate);

// Must undefine for UnityBuild or could get redefinition errors.
#undef IMPL_PRAGMA_METHOD
