// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.cpp.mustache
// </auto-generated>

#include "PragmaPlayerDataTypesDto.h"
#include "CoreMinimal.h"
#include "PragmaJson.h"



bool operator==(const FPragma_PlayerData_BigDataResponseProto& Lhs, const FPragma_PlayerData_BigDataResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_BigDataResponseProto& Lhs, const FPragma_PlayerData_BigDataResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DemoContentOperationResponseProto& Lhs, const FPragma_PlayerData_DemoContentOperationResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_DemoContentOperationResponseProto& Lhs, const FPragma_PlayerData_DemoContentOperationResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EmptyOperationResponseProto& Lhs, const FPragma_PlayerData_EmptyOperationResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_EmptyOperationResponseProto& Lhs, const FPragma_PlayerData_EmptyOperationResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DeleteNumberDataResponseProto& Lhs, const FPragma_PlayerData_DeleteNumberDataResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_DeleteNumberDataResponseProto& Lhs, const FPragma_PlayerData_DeleteNumberDataResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoResponseProto& Lhs, const FPragma_PlayerData_EchoResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Message == Rhs.Message
;
}
bool operator!=(const FPragma_PlayerData_EchoResponseProto& Lhs, const FPragma_PlayerData_EchoResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SomeServiceResponseProto& Lhs, const FPragma_PlayerData_SomeServiceResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SomeServiceResponseProto& Lhs, const FPragma_PlayerData_SomeServiceResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_MychecklistResponseOneProto& Lhs, const FPragma_PlayerData_MychecklistResponseOneProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.String == Rhs.String
;
}
bool operator!=(const FPragma_PlayerData_MychecklistResponseOneProto& Lhs, const FPragma_PlayerData_MychecklistResponseOneProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_GrantStarterItemsResponseProto& Lhs, const FPragma_PlayerData_GrantStarterItemsResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_GrantStarterItemsResponseProto& Lhs, const FPragma_PlayerData_GrantStarterItemsResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_ContentDrivenGrantsResponseProto& Lhs, const FPragma_PlayerData_ContentDrivenGrantsResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_ContentDrivenGrantsResponseProto& Lhs, const FPragma_PlayerData_ContentDrivenGrantsResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_AddNumberTimesTwoResponseProto& Lhs, const FPragma_PlayerData_AddNumberTimesTwoResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Total == Rhs.Total
;
}
bool operator!=(const FPragma_PlayerData_AddNumberTimesTwoResponseProto& Lhs, const FPragma_PlayerData_AddNumberTimesTwoResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_AddNumberResponseProto& Lhs, const FPragma_PlayerData_AddNumberResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Total == Rhs.Total
;
}
bool operator!=(const FPragma_PlayerData_AddNumberResponseProto& Lhs, const FPragma_PlayerData_AddNumberResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoListResponseProto& Lhs, const FPragma_PlayerData_EchoListResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.ListOfStrings == Rhs.ListOfStrings
;
}
bool operator!=(const FPragma_PlayerData_EchoListResponseProto& Lhs, const FPragma_PlayerData_EchoListResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SomeOperatorResponseProto& Lhs, const FPragma_PlayerData_SomeOperatorResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SomeOperatorResponseProto& Lhs, const FPragma_PlayerData_SomeOperatorResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_LoadTestEntityTransformResponseProto& Lhs, const FPragma_PlayerData_LoadTestEntityTransformResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_LoadTestEntityTransformResponseProto& Lhs, const FPragma_PlayerData_LoadTestEntityTransformResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SendEmptyPayloadResponseProto& Lhs, const FPragma_PlayerData_SendEmptyPayloadResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SendEmptyPayloadResponseProto& Lhs, const FPragma_PlayerData_SendEmptyPayloadResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_ManyComponentResponseProto& Lhs, const FPragma_PlayerData_ManyComponentResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_ManyComponentResponseProto& Lhs, const FPragma_PlayerData_ManyComponentResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_PlayerHiddenComponentResponseProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_PlayerHiddenComponentResponseProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SomeServiceRequestProto& Lhs, const FPragma_PlayerData_SomeServiceRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SomeServiceRequestProto& Lhs, const FPragma_PlayerData_SomeServiceRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_PlayerHiddenComponentRequestProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_PlayerHiddenComponentRequestProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_GrantStarterItemsRequestProto& Lhs, const FPragma_PlayerData_GrantStarterItemsRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_GrantStarterItemsRequestProto& Lhs, const FPragma_PlayerData_GrantStarterItemsRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_MyChecklistRequestOneProto& Lhs, const FPragma_PlayerData_MyChecklistRequestOneProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Int == Rhs.Int
;
}
bool operator!=(const FPragma_PlayerData_MyChecklistRequestOneProto& Lhs, const FPragma_PlayerData_MyChecklistRequestOneProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EmptyOperationRequestProto& Lhs, const FPragma_PlayerData_EmptyOperationRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_EmptyOperationRequestProto& Lhs, const FPragma_PlayerData_EmptyOperationRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_AddNumberTimesTwoRequestProto& Lhs, const FPragma_PlayerData_AddNumberTimesTwoRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Number == Rhs.Number
;
}
bool operator!=(const FPragma_PlayerData_AddNumberTimesTwoRequestProto& Lhs, const FPragma_PlayerData_AddNumberTimesTwoRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SomeOperatorRequestProto& Lhs, const FPragma_PlayerData_SomeOperatorRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SomeOperatorRequestProto& Lhs, const FPragma_PlayerData_SomeOperatorRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_SendEmptyPayloadRequestProto& Lhs, const FPragma_PlayerData_SendEmptyPayloadRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_SendEmptyPayloadRequestProto& Lhs, const FPragma_PlayerData_SendEmptyPayloadRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_AddNumberRequestProto& Lhs, const FPragma_PlayerData_AddNumberRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Number == Rhs.Number
;
}
bool operator!=(const FPragma_PlayerData_AddNumberRequestProto& Lhs, const FPragma_PlayerData_AddNumberRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_ManyComponentRequestProto& Lhs, const FPragma_PlayerData_ManyComponentRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_ManyComponentRequestProto& Lhs, const FPragma_PlayerData_ManyComponentRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DeleteNumberDataRequestProto& Lhs, const FPragma_PlayerData_DeleteNumberDataRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_DeleteNumberDataRequestProto& Lhs, const FPragma_PlayerData_DeleteNumberDataRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_ContentDrivenGrantsRequestProto& Lhs, const FPragma_PlayerData_ContentDrivenGrantsRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_ContentDrivenGrantsRequestProto& Lhs, const FPragma_PlayerData_ContentDrivenGrantsRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoListRequestProto& Lhs, const FPragma_PlayerData_EchoListRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.ListOfStrings == Rhs.ListOfStrings
;
}
bool operator!=(const FPragma_PlayerData_EchoListRequestProto& Lhs, const FPragma_PlayerData_EchoListRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_LoadTestEntityTransformRequestProto& Lhs, const FPragma_PlayerData_LoadTestEntityTransformRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_LoadTestEntityTransformRequestProto& Lhs, const FPragma_PlayerData_LoadTestEntityTransformRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoRequestProto& Lhs, const FPragma_PlayerData_EchoRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Message == Rhs.Message
;
}
bool operator!=(const FPragma_PlayerData_EchoRequestProto& Lhs, const FPragma_PlayerData_EchoRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DemoContentOperationRequestProto& Lhs, const FPragma_PlayerData_DemoContentOperationRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_DemoContentOperationRequestProto& Lhs, const FPragma_PlayerData_DemoContentOperationRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_BigDataRequestProto& Lhs, const FPragma_PlayerData_BigDataRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_BigDataRequestProto& Lhs, const FPragma_PlayerData_BigDataRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_PlayerVisibleComponentProto& Lhs, const FPragma_PlayerData_PlayerVisibleComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_PlayerVisibleComponentProto& Lhs, const FPragma_PlayerData_PlayerVisibleComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_MyComponentProto& Lhs, const FPragma_PlayerData_MyComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Num == Rhs.Num
			&& Lhs.Str == Rhs.Str
;
}
bool operator!=(const FPragma_PlayerData_MyComponentProto& Lhs, const FPragma_PlayerData_MyComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_WalletComponentProto& Lhs, const FPragma_PlayerData_WalletComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Gold == Rhs.Gold
;
}
bool operator!=(const FPragma_PlayerData_WalletComponentProto& Lhs, const FPragma_PlayerData_WalletComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_StringComponentProto& Lhs, const FPragma_PlayerData_StringComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Value == Rhs.Value
;
}
bool operator!=(const FPragma_PlayerData_StringComponentProto& Lhs, const FPragma_PlayerData_StringComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_NumberDataProto& Lhs, const FPragma_PlayerData_NumberDataProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Number == Rhs.Number
;
}
bool operator!=(const FPragma_PlayerData_NumberDataProto& Lhs, const FPragma_PlayerData_NumberDataProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DemoContainedTypeProto& Lhs, const FPragma_PlayerData_DemoContainedTypeProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Number == Rhs.Number
			&& Lhs.Word == Rhs.Word
;
}
bool operator!=(const FPragma_PlayerData_DemoContainedTypeProto& Lhs, const FPragma_PlayerData_DemoContainedTypeProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DemoNestedTypeProto& Lhs, const FPragma_PlayerData_DemoNestedTypeProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.DemoList == Rhs.DemoList
			&& Lhs.DemoMap.OrderIndependentCompareEqual(Rhs.DemoMap)
			&& Lhs.DemoMutableList == Rhs.DemoMutableList
			&& Lhs.DemoMutableMap.OrderIndependentCompareEqual(Rhs.DemoMutableMap)
			&& Lhs.Uuid == Rhs.Uuid
;
}
bool operator!=(const FPragma_PlayerData_DemoNestedTypeProto& Lhs, const FPragma_PlayerData_DemoNestedTypeProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_DemoComplexTypeProto& Lhs, const FPragma_PlayerData_DemoComplexTypeProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.DemoList == Rhs.DemoList
			&& Lhs.DemoListInt == Rhs.DemoListInt
			&& Lhs.DemoListString == Rhs.DemoListString
			&& Lhs.DemoMap.OrderIndependentCompareEqual(Rhs.DemoMap)
			&& Lhs.DemoMutableList == Rhs.DemoMutableList
			&& Lhs.DemoMutableMap.OrderIndependentCompareEqual(Rhs.DemoMutableMap)
			&& Lhs.NestedType == Rhs.NestedType
			&& Lhs.Uuid == Rhs.Uuid
;
}
bool operator!=(const FPragma_PlayerData_DemoComplexTypeProto& Lhs, const FPragma_PlayerData_DemoComplexTypeProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoComplexResponseProto& Lhs, const FPragma_PlayerData_EchoComplexResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.DemoComplexType == Rhs.DemoComplexType
;
}
bool operator!=(const FPragma_PlayerData_EchoComplexResponseProto& Lhs, const FPragma_PlayerData_EchoComplexResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}

FPragma_PlayerData_PlayerDataResponseProto_Payload::FPragma_PlayerData_PlayerDataResponseProto_Payload() {}
FPragma_PlayerData_PlayerDataResponseProto_Payload::~FPragma_PlayerData_PlayerDataResponseProto_Payload()
{
	Reset();
}

FPragma_PlayerData_PlayerDataResponseProto_Payload::FPragma_PlayerData_PlayerDataResponseProto_Payload(const FPragma_PlayerData_PlayerDataResponseProto_Payload& Other)
{
	*this = Other;
}

bool FPragma_PlayerData_PlayerDataResponseProto_Payload::Equals(const FPragma_PlayerData_PlayerDataResponseProto_Payload& Other) const
{
    if (OneOfType() != Other.OneOfType())
    {
        return false;
    }
	switch (OneOfType())
	{
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber:
		return AddNumber() == Other.AddNumber();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo:
		return AddNumberTimesTwo() == Other.AddNumberTimesTwo();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity:
		return BigDataEntity() == Other.BigDataEntity();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants:
		return ContentDrivenGrants() == Other.ContentDrivenGrants();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData:
		return DeleteNumberData() == Other.DeleteNumberData();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation:
		return DemoContentOperation() == Other.DemoContentOperation();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo:
		return Echo() == Other.Echo();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex:
		return EchoComplex() == Other.EchoComplex();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList:
		return EchoList() == Other.EchoList();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation:
		return EmptyOperation() == Other.EmptyOperation();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems:
		return GrantStarterItems() == Other.GrantStarterItems();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer:
		return HideStuffFromPlayer() == Other.HideStuffFromPlayer();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform:
		return LoadTestEntityTransform() == Other.LoadTestEntityTransform();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity:
		return ManyComponentEntity() == Other.ManyComponentEntity();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation:
		return MyOperation() == Other.MyOperation();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload:
		return SendEmptyPayload() == Other.SendEmptyPayload();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne:
		return SomeOperatorOne() == Other.SomeOperatorOne();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne:
		return SomeServiceOne() == Other.SomeServiceOne();
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Invalid:
        return true;
	default:
		return false;
	}
}

FPragma_PlayerData_PlayerDataResponseProto_Payload& FPragma_PlayerData_PlayerDataResponseProto_Payload::operator=(const FPragma_PlayerData_PlayerDataResponseProto_Payload& Other)
{
	Reset();
	Type = Other.OneOfType();
	switch (Other.OneOfType())
	{
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber:
		new(Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberResponseProto(Other.AddNumber());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo:
		new(Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoResponseProto(Other.AddNumberTimesTwo());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity:
		new(Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataResponseProto(Other.BigDataEntity());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants:
		new(Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsResponseProto(Other.ContentDrivenGrants());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData:
		new(Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataResponseProto(Other.DeleteNumberData());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation:
		new(Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationResponseProto(Other.DemoContentOperation());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo:
		new(Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoResponseProto(Other.Echo());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex:
		new(Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexResponseProto(Other.EchoComplex());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList:
		new(Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListResponseProto(Other.EchoList());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation:
		new(Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationResponseProto(Other.EmptyOperation());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems:
		new(Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsResponseProto(Other.GrantStarterItems());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer:
		new(Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentResponseProto(Other.HideStuffFromPlayer());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform:
		new(Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformResponseProto(Other.LoadTestEntityTransform());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity:
		new(Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentResponseProto(Other.ManyComponentEntity());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation:
		new(Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MychecklistResponseOneProto(Other.MyOperation());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload:
		new(Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadResponseProto(Other.SendEmptyPayload());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne:
		new(Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorResponseProto(Other.SomeOperatorOne());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne:
		new(Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceResponseProto(Other.SomeServiceOne());
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Invalid:
	default:
		break;
	}
	return *this;
}

void FPragma_PlayerData_PlayerDataResponseProto_Payload::Reset()
{
	switch (OneOfType())
	{
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber:
		Union.AddNumber.GetTypedPtr()->~FPragma_PlayerData_AddNumberResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo:
		Union.AddNumberTimesTwo.GetTypedPtr()->~FPragma_PlayerData_AddNumberTimesTwoResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity:
		Union.BigDataEntity.GetTypedPtr()->~FPragma_PlayerData_BigDataResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants:
		Union.ContentDrivenGrants.GetTypedPtr()->~FPragma_PlayerData_ContentDrivenGrantsResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData:
		Union.DeleteNumberData.GetTypedPtr()->~FPragma_PlayerData_DeleteNumberDataResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation:
		Union.DemoContentOperation.GetTypedPtr()->~FPragma_PlayerData_DemoContentOperationResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo:
		Union.Echo.GetTypedPtr()->~FPragma_PlayerData_EchoResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex:
		Union.EchoComplex.GetTypedPtr()->~FPragma_PlayerData_EchoComplexResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList:
		Union.EchoList.GetTypedPtr()->~FPragma_PlayerData_EchoListResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation:
		Union.EmptyOperation.GetTypedPtr()->~FPragma_PlayerData_EmptyOperationResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems:
		Union.GrantStarterItems.GetTypedPtr()->~FPragma_PlayerData_GrantStarterItemsResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer:
		Union.HideStuffFromPlayer.GetTypedPtr()->~FPragma_PlayerData_PlayerHiddenComponentResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform:
		Union.LoadTestEntityTransform.GetTypedPtr()->~FPragma_PlayerData_LoadTestEntityTransformResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity:
		Union.ManyComponentEntity.GetTypedPtr()->~FPragma_PlayerData_ManyComponentResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation:
		Union.MyOperation.GetTypedPtr()->~FPragma_PlayerData_MychecklistResponseOneProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload:
		Union.SendEmptyPayload.GetTypedPtr()->~FPragma_PlayerData_SendEmptyPayloadResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne:
		Union.SomeOperatorOne.GetTypedPtr()->~FPragma_PlayerData_SomeOperatorResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne:
		Union.SomeServiceOne.GetTypedPtr()->~FPragma_PlayerData_SomeServiceResponseProto();
		break;
	case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Invalid:
	default:
		break;
	}
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Invalid;
}

const FPragma_PlayerData_AddNumberResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::AddNumber() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber, TEXT("Failed to retrieve AddNumber from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.AddNumber.GetTypedPtr();
}
const FPragma_PlayerData_AddNumberTimesTwoResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::AddNumberTimesTwo() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo, TEXT("Failed to retrieve AddNumberTimesTwo from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.AddNumberTimesTwo.GetTypedPtr();
}
const FPragma_PlayerData_BigDataResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::BigDataEntity() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity, TEXT("Failed to retrieve BigDataEntity from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.BigDataEntity.GetTypedPtr();
}
const FPragma_PlayerData_ContentDrivenGrantsResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::ContentDrivenGrants() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants, TEXT("Failed to retrieve ContentDrivenGrants from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.ContentDrivenGrants.GetTypedPtr();
}
const FPragma_PlayerData_DeleteNumberDataResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::DeleteNumberData() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData, TEXT("Failed to retrieve DeleteNumberData from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.DeleteNumberData.GetTypedPtr();
}
const FPragma_PlayerData_DemoContentOperationResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::DemoContentOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation, TEXT("Failed to retrieve DemoContentOperation from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.DemoContentOperation.GetTypedPtr();
}
const FPragma_PlayerData_EchoResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::Echo() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo, TEXT("Failed to retrieve Echo from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.Echo.GetTypedPtr();
}
const FPragma_PlayerData_EchoComplexResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::EchoComplex() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex, TEXT("Failed to retrieve EchoComplex from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EchoComplex.GetTypedPtr();
}
const FPragma_PlayerData_EchoListResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::EchoList() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList, TEXT("Failed to retrieve EchoList from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EchoList.GetTypedPtr();
}
const FPragma_PlayerData_EmptyOperationResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::EmptyOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation, TEXT("Failed to retrieve EmptyOperation from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EmptyOperation.GetTypedPtr();
}
const FPragma_PlayerData_GrantStarterItemsResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::GrantStarterItems() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems, TEXT("Failed to retrieve GrantStarterItems from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.GrantStarterItems.GetTypedPtr();
}
const FPragma_PlayerData_PlayerHiddenComponentResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::HideStuffFromPlayer() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer, TEXT("Failed to retrieve HideStuffFromPlayer from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.HideStuffFromPlayer.GetTypedPtr();
}
const FPragma_PlayerData_LoadTestEntityTransformResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::LoadTestEntityTransform() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform, TEXT("Failed to retrieve LoadTestEntityTransform from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.LoadTestEntityTransform.GetTypedPtr();
}
const FPragma_PlayerData_ManyComponentResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::ManyComponentEntity() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity, TEXT("Failed to retrieve ManyComponentEntity from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.ManyComponentEntity.GetTypedPtr();
}
const FPragma_PlayerData_MychecklistResponseOneProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::MyOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation, TEXT("Failed to retrieve MyOperation from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.MyOperation.GetTypedPtr();
}
const FPragma_PlayerData_SendEmptyPayloadResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::SendEmptyPayload() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload, TEXT("Failed to retrieve SendEmptyPayload from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SendEmptyPayload.GetTypedPtr();
}
const FPragma_PlayerData_SomeOperatorResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::SomeOperatorOne() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne, TEXT("Failed to retrieve SomeOperatorOne from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SomeOperatorOne.GetTypedPtr();
}
const FPragma_PlayerData_SomeServiceResponseProto& FPragma_PlayerData_PlayerDataResponseProto_Payload::SomeServiceOne() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne, TEXT("Failed to retrieve SomeServiceOne from FPragma_PlayerData_PlayerDataResponseProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SomeServiceOne.GetTypedPtr();
}

void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetAddNumber(const FPragma_PlayerData_AddNumberResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber;
	new(Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetAddNumberTimesTwo(const FPragma_PlayerData_AddNumberTimesTwoResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo;
	new(Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetBigDataEntity(const FPragma_PlayerData_BigDataResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity;
	new(Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetContentDrivenGrants(const FPragma_PlayerData_ContentDrivenGrantsResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants;
	new(Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetDeleteNumberData(const FPragma_PlayerData_DeleteNumberDataResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData;
	new(Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetDemoContentOperation(const FPragma_PlayerData_DemoContentOperationResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation;
	new(Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetEcho(const FPragma_PlayerData_EchoResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo;
	new(Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetEchoComplex(const FPragma_PlayerData_EchoComplexResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex;
	new(Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetEchoList(const FPragma_PlayerData_EchoListResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList;
	new(Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetEmptyOperation(const FPragma_PlayerData_EmptyOperationResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation;
	new(Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetGrantStarterItems(const FPragma_PlayerData_GrantStarterItemsResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems;
	new(Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetHideStuffFromPlayer(const FPragma_PlayerData_PlayerHiddenComponentResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer;
	new(Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetLoadTestEntityTransform(const FPragma_PlayerData_LoadTestEntityTransformResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform;
	new(Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetManyComponentEntity(const FPragma_PlayerData_ManyComponentResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity;
	new(Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetMyOperation(const FPragma_PlayerData_MychecklistResponseOneProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation;
	new(Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MychecklistResponseOneProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetSendEmptyPayload(const FPragma_PlayerData_SendEmptyPayloadResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload;
	new(Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetSomeOperatorOne(const FPragma_PlayerData_SomeOperatorResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne;
	new(Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorResponseProto(Value);
}
void FPragma_PlayerData_PlayerDataResponseProto_Payload::SetSomeServiceOne(const FPragma_PlayerData_SomeServiceResponseProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne;
	new(Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceResponseProto(Value);
}

bool FPragma_PlayerData_PlayerDataResponseProto_Payload::SerializeIntoParentJson(const void* Value, TSharedRef<FJsonObject>& OutJsonObj)
{
	const FPragma_PlayerData_PlayerDataResponseProto_Payload& OneOf = static_cast<const FPragma_PlayerData_PlayerDataResponseProto*>(Value)->Payload;
	switch (OneOf.OneOfType())
	{
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber:
			OutJsonObj->SetField("addNumber", PragmaJson::StructToJsonValue(*OneOf.Union.AddNumber.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo:
			OutJsonObj->SetField("addNumberTimesTwo", PragmaJson::StructToJsonValue(*OneOf.Union.AddNumberTimesTwo.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity:
			OutJsonObj->SetField("bigDataEntity", PragmaJson::StructToJsonValue(*OneOf.Union.BigDataEntity.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants:
			OutJsonObj->SetField("contentDrivenGrants", PragmaJson::StructToJsonValue(*OneOf.Union.ContentDrivenGrants.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData:
			OutJsonObj->SetField("deleteNumberData", PragmaJson::StructToJsonValue(*OneOf.Union.DeleteNumberData.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation:
			OutJsonObj->SetField("demoContentOperation", PragmaJson::StructToJsonValue(*OneOf.Union.DemoContentOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo:
			OutJsonObj->SetField("echo", PragmaJson::StructToJsonValue(*OneOf.Union.Echo.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex:
			OutJsonObj->SetField("echoComplex", PragmaJson::StructToJsonValue(*OneOf.Union.EchoComplex.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList:
			OutJsonObj->SetField("echoList", PragmaJson::StructToJsonValue(*OneOf.Union.EchoList.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation:
			OutJsonObj->SetField("emptyOperation", PragmaJson::StructToJsonValue(*OneOf.Union.EmptyOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems:
			OutJsonObj->SetField("grantStarterItems", PragmaJson::StructToJsonValue(*OneOf.Union.GrantStarterItems.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer:
			OutJsonObj->SetField("hideStuffFromPlayer", PragmaJson::StructToJsonValue(*OneOf.Union.HideStuffFromPlayer.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform:
			OutJsonObj->SetField("loadTestEntityTransform", PragmaJson::StructToJsonValue(*OneOf.Union.LoadTestEntityTransform.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity:
			OutJsonObj->SetField("manyComponentEntity", PragmaJson::StructToJsonValue(*OneOf.Union.ManyComponentEntity.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation:
			OutJsonObj->SetField("myOperation", PragmaJson::StructToJsonValue(*OneOf.Union.MyOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload:
			OutJsonObj->SetField("sendEmptyPayload", PragmaJson::StructToJsonValue(*OneOf.Union.SendEmptyPayload.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne:
			OutJsonObj->SetField("someOperatorOne", PragmaJson::StructToJsonValue(*OneOf.Union.SomeOperatorOne.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne:
			OutJsonObj->SetField("someServiceOne", PragmaJson::StructToJsonValue(*OneOf.Union.SomeServiceOne.GetTypedPtr()));
			break;
		default:
			break;
	}
	// Per protobuf spec, it's ok to have empty oneof.
	return true;
}
bool FPragma_PlayerData_PlayerDataResponseProto_Payload::DeserializeFromParentJson(const TSharedRef<FJsonObject>& JsonObj, void* OutValue)
{
	FPragma_PlayerData_PlayerDataResponseProto_Payload& OutOneOf = static_cast<FPragma_PlayerData_PlayerDataResponseProto*>(OutValue)->Payload;
	if (JsonObj->HasField("addNumber"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumber;
		new(OutOneOf.Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_AddNumberResponseProto>(JsonObj->TryGetField(TEXT("addNumber")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("addNumberTimesTwo"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::AddNumberTimesTwo;
		new(OutOneOf.Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_AddNumberTimesTwoResponseProto>(JsonObj->TryGetField(TEXT("addNumberTimesTwo")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("bigDataEntity"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::BigDataEntity;
		new(OutOneOf.Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_BigDataResponseProto>(JsonObj->TryGetField(TEXT("bigDataEntity")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("contentDrivenGrants"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ContentDrivenGrants;
		new(OutOneOf.Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_ContentDrivenGrantsResponseProto>(JsonObj->TryGetField(TEXT("contentDrivenGrants")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("deleteNumberData"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DeleteNumberData;
		new(OutOneOf.Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_DeleteNumberDataResponseProto>(JsonObj->TryGetField(TEXT("deleteNumberData")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("demoContentOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::DemoContentOperation;
		new(OutOneOf.Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_DemoContentOperationResponseProto>(JsonObj->TryGetField(TEXT("demoContentOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echo"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::Echo;
		new(OutOneOf.Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoResponseProto>(JsonObj->TryGetField(TEXT("echo")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echoComplex"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoComplex;
		new(OutOneOf.Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoComplexResponseProto>(JsonObj->TryGetField(TEXT("echoComplex")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echoList"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EchoList;
		new(OutOneOf.Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoListResponseProto>(JsonObj->TryGetField(TEXT("echoList")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("emptyOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::EmptyOperation;
		new(OutOneOf.Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EmptyOperationResponseProto>(JsonObj->TryGetField(TEXT("emptyOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("grantStarterItems"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::GrantStarterItems;
		new(OutOneOf.Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_GrantStarterItemsResponseProto>(JsonObj->TryGetField(TEXT("grantStarterItems")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("hideStuffFromPlayer"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::HideStuffFromPlayer;
		new(OutOneOf.Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_PlayerHiddenComponentResponseProto>(JsonObj->TryGetField(TEXT("hideStuffFromPlayer")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("loadTestEntityTransform"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::LoadTestEntityTransform;
		new(OutOneOf.Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_LoadTestEntityTransformResponseProto>(JsonObj->TryGetField(TEXT("loadTestEntityTransform")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("manyComponentEntity"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::ManyComponentEntity;
		new(OutOneOf.Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_ManyComponentResponseProto>(JsonObj->TryGetField(TEXT("manyComponentEntity")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("myOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::MyOperation;
		new(OutOneOf.Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MychecklistResponseOneProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_MychecklistResponseOneProto>(JsonObj->TryGetField(TEXT("myOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("sendEmptyPayload"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SendEmptyPayload;
		new(OutOneOf.Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SendEmptyPayloadResponseProto>(JsonObj->TryGetField(TEXT("sendEmptyPayload")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("someOperatorOne"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeOperatorOne;
		new(OutOneOf.Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SomeOperatorResponseProto>(JsonObj->TryGetField(TEXT("someOperatorOne")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("someServiceOne"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataResponseProto_PayloadType::SomeServiceOne;
		new(OutOneOf.Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceResponseProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SomeServiceResponseProto>(JsonObj->TryGetField(TEXT("someServiceOne")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	// Per protobuf spec, oneofs have _at most_ one of the fields. None set is valid, so we always return true.
	return true;
}

bool operator==(const FPragma_PlayerData_PlayerDataResponseProto_Payload& Lhs, const FPragma_PlayerData_PlayerDataResponseProto_Payload& Rhs)
{
	return Lhs.Equals(Rhs);
}
bool operator!=(const FPragma_PlayerData_PlayerDataResponseProto_Payload& Lhs, const FPragma_PlayerData_PlayerDataResponseProto_Payload& Rhs)
{
	return !(Lhs == Rhs);
}


bool FPragma_PlayerData_PlayerDataResponseProto::AddonSerializer(const void* Value, TSharedRef<FJsonObject>& OutJsonObj)
{
	bool Success = true;
	Success &= FPragma_PlayerData_PlayerDataResponseProto_Payload::SerializeIntoParentJson(Value, OutJsonObj);
	return Success;
}

bool FPragma_PlayerData_PlayerDataResponseProto::AddonDeserializer(const TSharedRef<FJsonObject>& JsonObj, void* OutValue)
{
	bool Success = true;
	Success &= FPragma_PlayerData_PlayerDataResponseProto_Payload::DeserializeFromParentJson(JsonObj, OutValue);
	return Success;
}

bool operator==(const FPragma_PlayerData_PlayerDataResponseProto& Lhs, const FPragma_PlayerData_PlayerDataResponseProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Payload == Rhs.Payload
;
}
bool operator!=(const FPragma_PlayerData_PlayerDataResponseProto& Lhs, const FPragma_PlayerData_PlayerDataResponseProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_EchoComplexRequestProto& Lhs, const FPragma_PlayerData_EchoComplexRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.DemoComplexType == Rhs.DemoComplexType
;
}
bool operator!=(const FPragma_PlayerData_EchoComplexRequestProto& Lhs, const FPragma_PlayerData_EchoComplexRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}

FPragma_PlayerData_PlayerDataRequestProto_Payload::FPragma_PlayerData_PlayerDataRequestProto_Payload() {}
FPragma_PlayerData_PlayerDataRequestProto_Payload::~FPragma_PlayerData_PlayerDataRequestProto_Payload()
{
	Reset();
}

FPragma_PlayerData_PlayerDataRequestProto_Payload::FPragma_PlayerData_PlayerDataRequestProto_Payload(const FPragma_PlayerData_PlayerDataRequestProto_Payload& Other)
{
	*this = Other;
}

bool FPragma_PlayerData_PlayerDataRequestProto_Payload::Equals(const FPragma_PlayerData_PlayerDataRequestProto_Payload& Other) const
{
    if (OneOfType() != Other.OneOfType())
    {
        return false;
    }
	switch (OneOfType())
	{
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber:
		return AddNumber() == Other.AddNumber();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo:
		return AddNumberTimesTwo() == Other.AddNumberTimesTwo();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity:
		return BigDataEntity() == Other.BigDataEntity();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants:
		return ContentDrivenGrants() == Other.ContentDrivenGrants();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData:
		return DeleteNumberData() == Other.DeleteNumberData();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation:
		return DemoContentOperation() == Other.DemoContentOperation();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo:
		return Echo() == Other.Echo();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex:
		return EchoComplex() == Other.EchoComplex();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList:
		return EchoList() == Other.EchoList();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation:
		return EmptyOperation() == Other.EmptyOperation();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems:
		return GrantStarterItems() == Other.GrantStarterItems();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer:
		return HideStuffFromPlayer() == Other.HideStuffFromPlayer();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform:
		return LoadTestEntityTransform() == Other.LoadTestEntityTransform();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity:
		return ManyComponentEntity() == Other.ManyComponentEntity();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation:
		return MyOperation() == Other.MyOperation();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload:
		return SendEmptyPayload() == Other.SendEmptyPayload();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne:
		return SomeOperatorOne() == Other.SomeOperatorOne();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne:
		return SomeServiceOne() == Other.SomeServiceOne();
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Invalid:
        return true;
	default:
		return false;
	}
}

FPragma_PlayerData_PlayerDataRequestProto_Payload& FPragma_PlayerData_PlayerDataRequestProto_Payload::operator=(const FPragma_PlayerData_PlayerDataRequestProto_Payload& Other)
{
	Reset();
	Type = Other.OneOfType();
	switch (Other.OneOfType())
	{
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber:
		new(Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberRequestProto(Other.AddNumber());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo:
		new(Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoRequestProto(Other.AddNumberTimesTwo());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity:
		new(Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataRequestProto(Other.BigDataEntity());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants:
		new(Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsRequestProto(Other.ContentDrivenGrants());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData:
		new(Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataRequestProto(Other.DeleteNumberData());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation:
		new(Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationRequestProto(Other.DemoContentOperation());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo:
		new(Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoRequestProto(Other.Echo());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex:
		new(Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexRequestProto(Other.EchoComplex());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList:
		new(Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListRequestProto(Other.EchoList());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation:
		new(Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationRequestProto(Other.EmptyOperation());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems:
		new(Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsRequestProto(Other.GrantStarterItems());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer:
		new(Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentRequestProto(Other.HideStuffFromPlayer());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform:
		new(Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformRequestProto(Other.LoadTestEntityTransform());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity:
		new(Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentRequestProto(Other.ManyComponentEntity());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation:
		new(Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MyChecklistRequestOneProto(Other.MyOperation());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload:
		new(Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadRequestProto(Other.SendEmptyPayload());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne:
		new(Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorRequestProto(Other.SomeOperatorOne());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne:
		new(Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceRequestProto(Other.SomeServiceOne());
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Invalid:
	default:
		break;
	}
	return *this;
}

void FPragma_PlayerData_PlayerDataRequestProto_Payload::Reset()
{
	switch (OneOfType())
	{
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber:
		Union.AddNumber.GetTypedPtr()->~FPragma_PlayerData_AddNumberRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo:
		Union.AddNumberTimesTwo.GetTypedPtr()->~FPragma_PlayerData_AddNumberTimesTwoRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity:
		Union.BigDataEntity.GetTypedPtr()->~FPragma_PlayerData_BigDataRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants:
		Union.ContentDrivenGrants.GetTypedPtr()->~FPragma_PlayerData_ContentDrivenGrantsRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData:
		Union.DeleteNumberData.GetTypedPtr()->~FPragma_PlayerData_DeleteNumberDataRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation:
		Union.DemoContentOperation.GetTypedPtr()->~FPragma_PlayerData_DemoContentOperationRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo:
		Union.Echo.GetTypedPtr()->~FPragma_PlayerData_EchoRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex:
		Union.EchoComplex.GetTypedPtr()->~FPragma_PlayerData_EchoComplexRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList:
		Union.EchoList.GetTypedPtr()->~FPragma_PlayerData_EchoListRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation:
		Union.EmptyOperation.GetTypedPtr()->~FPragma_PlayerData_EmptyOperationRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems:
		Union.GrantStarterItems.GetTypedPtr()->~FPragma_PlayerData_GrantStarterItemsRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer:
		Union.HideStuffFromPlayer.GetTypedPtr()->~FPragma_PlayerData_PlayerHiddenComponentRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform:
		Union.LoadTestEntityTransform.GetTypedPtr()->~FPragma_PlayerData_LoadTestEntityTransformRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity:
		Union.ManyComponentEntity.GetTypedPtr()->~FPragma_PlayerData_ManyComponentRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation:
		Union.MyOperation.GetTypedPtr()->~FPragma_PlayerData_MyChecklistRequestOneProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload:
		Union.SendEmptyPayload.GetTypedPtr()->~FPragma_PlayerData_SendEmptyPayloadRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne:
		Union.SomeOperatorOne.GetTypedPtr()->~FPragma_PlayerData_SomeOperatorRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne:
		Union.SomeServiceOne.GetTypedPtr()->~FPragma_PlayerData_SomeServiceRequestProto();
		break;
	case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Invalid:
	default:
		break;
	}
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Invalid;
}

const FPragma_PlayerData_AddNumberRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::AddNumber() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber, TEXT("Failed to retrieve AddNumber from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.AddNumber.GetTypedPtr();
}
const FPragma_PlayerData_AddNumberTimesTwoRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::AddNumberTimesTwo() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo, TEXT("Failed to retrieve AddNumberTimesTwo from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.AddNumberTimesTwo.GetTypedPtr();
}
const FPragma_PlayerData_BigDataRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::BigDataEntity() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity, TEXT("Failed to retrieve BigDataEntity from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.BigDataEntity.GetTypedPtr();
}
const FPragma_PlayerData_ContentDrivenGrantsRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::ContentDrivenGrants() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants, TEXT("Failed to retrieve ContentDrivenGrants from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.ContentDrivenGrants.GetTypedPtr();
}
const FPragma_PlayerData_DeleteNumberDataRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::DeleteNumberData() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData, TEXT("Failed to retrieve DeleteNumberData from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.DeleteNumberData.GetTypedPtr();
}
const FPragma_PlayerData_DemoContentOperationRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::DemoContentOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation, TEXT("Failed to retrieve DemoContentOperation from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.DemoContentOperation.GetTypedPtr();
}
const FPragma_PlayerData_EchoRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::Echo() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo, TEXT("Failed to retrieve Echo from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.Echo.GetTypedPtr();
}
const FPragma_PlayerData_EchoComplexRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::EchoComplex() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex, TEXT("Failed to retrieve EchoComplex from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EchoComplex.GetTypedPtr();
}
const FPragma_PlayerData_EchoListRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::EchoList() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList, TEXT("Failed to retrieve EchoList from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EchoList.GetTypedPtr();
}
const FPragma_PlayerData_EmptyOperationRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::EmptyOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation, TEXT("Failed to retrieve EmptyOperation from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.EmptyOperation.GetTypedPtr();
}
const FPragma_PlayerData_GrantStarterItemsRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::GrantStarterItems() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems, TEXT("Failed to retrieve GrantStarterItems from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.GrantStarterItems.GetTypedPtr();
}
const FPragma_PlayerData_PlayerHiddenComponentRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::HideStuffFromPlayer() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer, TEXT("Failed to retrieve HideStuffFromPlayer from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.HideStuffFromPlayer.GetTypedPtr();
}
const FPragma_PlayerData_LoadTestEntityTransformRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::LoadTestEntityTransform() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform, TEXT("Failed to retrieve LoadTestEntityTransform from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.LoadTestEntityTransform.GetTypedPtr();
}
const FPragma_PlayerData_ManyComponentRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::ManyComponentEntity() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity, TEXT("Failed to retrieve ManyComponentEntity from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.ManyComponentEntity.GetTypedPtr();
}
const FPragma_PlayerData_MyChecklistRequestOneProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::MyOperation() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation, TEXT("Failed to retrieve MyOperation from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.MyOperation.GetTypedPtr();
}
const FPragma_PlayerData_SendEmptyPayloadRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::SendEmptyPayload() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload, TEXT("Failed to retrieve SendEmptyPayload from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SendEmptyPayload.GetTypedPtr();
}
const FPragma_PlayerData_SomeOperatorRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::SomeOperatorOne() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne, TEXT("Failed to retrieve SomeOperatorOne from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SomeOperatorOne.GetTypedPtr();
}
const FPragma_PlayerData_SomeServiceRequestProto& FPragma_PlayerData_PlayerDataRequestProto_Payload::SomeServiceOne() const {
	checkf(OneOfType() == EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne, TEXT("Failed to retrieve SomeServiceOne from FPragma_PlayerData_PlayerDataRequestProto_Payload. Check the OneOfType() before accessing the value."));
	return *Union.SomeServiceOne.GetTypedPtr();
}

void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetAddNumber(const FPragma_PlayerData_AddNumberRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber;
	new(Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetAddNumberTimesTwo(const FPragma_PlayerData_AddNumberTimesTwoRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo;
	new(Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetBigDataEntity(const FPragma_PlayerData_BigDataRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity;
	new(Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetContentDrivenGrants(const FPragma_PlayerData_ContentDrivenGrantsRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants;
	new(Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetDeleteNumberData(const FPragma_PlayerData_DeleteNumberDataRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData;
	new(Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetDemoContentOperation(const FPragma_PlayerData_DemoContentOperationRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation;
	new(Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetEcho(const FPragma_PlayerData_EchoRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo;
	new(Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetEchoComplex(const FPragma_PlayerData_EchoComplexRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex;
	new(Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetEchoList(const FPragma_PlayerData_EchoListRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList;
	new(Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetEmptyOperation(const FPragma_PlayerData_EmptyOperationRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation;
	new(Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetGrantStarterItems(const FPragma_PlayerData_GrantStarterItemsRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems;
	new(Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetHideStuffFromPlayer(const FPragma_PlayerData_PlayerHiddenComponentRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer;
	new(Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetLoadTestEntityTransform(const FPragma_PlayerData_LoadTestEntityTransformRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform;
	new(Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetManyComponentEntity(const FPragma_PlayerData_ManyComponentRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity;
	new(Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetMyOperation(const FPragma_PlayerData_MyChecklistRequestOneProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation;
	new(Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MyChecklistRequestOneProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetSendEmptyPayload(const FPragma_PlayerData_SendEmptyPayloadRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload;
	new(Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetSomeOperatorOne(const FPragma_PlayerData_SomeOperatorRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne;
	new(Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorRequestProto(Value);
}
void FPragma_PlayerData_PlayerDataRequestProto_Payload::SetSomeServiceOne(const FPragma_PlayerData_SomeServiceRequestProto& Value)
{
	Reset();
	Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne;
	new(Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceRequestProto(Value);
}

bool FPragma_PlayerData_PlayerDataRequestProto_Payload::SerializeIntoParentJson(const void* Value, TSharedRef<FJsonObject>& OutJsonObj)
{
	const FPragma_PlayerData_PlayerDataRequestProto_Payload& OneOf = static_cast<const FPragma_PlayerData_PlayerDataRequestProto*>(Value)->Payload;
	switch (OneOf.OneOfType())
	{
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber:
			OutJsonObj->SetField("addNumber", PragmaJson::StructToJsonValue(*OneOf.Union.AddNumber.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo:
			OutJsonObj->SetField("addNumberTimesTwo", PragmaJson::StructToJsonValue(*OneOf.Union.AddNumberTimesTwo.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity:
			OutJsonObj->SetField("bigDataEntity", PragmaJson::StructToJsonValue(*OneOf.Union.BigDataEntity.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants:
			OutJsonObj->SetField("contentDrivenGrants", PragmaJson::StructToJsonValue(*OneOf.Union.ContentDrivenGrants.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData:
			OutJsonObj->SetField("deleteNumberData", PragmaJson::StructToJsonValue(*OneOf.Union.DeleteNumberData.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation:
			OutJsonObj->SetField("demoContentOperation", PragmaJson::StructToJsonValue(*OneOf.Union.DemoContentOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo:
			OutJsonObj->SetField("echo", PragmaJson::StructToJsonValue(*OneOf.Union.Echo.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex:
			OutJsonObj->SetField("echoComplex", PragmaJson::StructToJsonValue(*OneOf.Union.EchoComplex.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList:
			OutJsonObj->SetField("echoList", PragmaJson::StructToJsonValue(*OneOf.Union.EchoList.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation:
			OutJsonObj->SetField("emptyOperation", PragmaJson::StructToJsonValue(*OneOf.Union.EmptyOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems:
			OutJsonObj->SetField("grantStarterItems", PragmaJson::StructToJsonValue(*OneOf.Union.GrantStarterItems.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer:
			OutJsonObj->SetField("hideStuffFromPlayer", PragmaJson::StructToJsonValue(*OneOf.Union.HideStuffFromPlayer.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform:
			OutJsonObj->SetField("loadTestEntityTransform", PragmaJson::StructToJsonValue(*OneOf.Union.LoadTestEntityTransform.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity:
			OutJsonObj->SetField("manyComponentEntity", PragmaJson::StructToJsonValue(*OneOf.Union.ManyComponentEntity.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation:
			OutJsonObj->SetField("myOperation", PragmaJson::StructToJsonValue(*OneOf.Union.MyOperation.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload:
			OutJsonObj->SetField("sendEmptyPayload", PragmaJson::StructToJsonValue(*OneOf.Union.SendEmptyPayload.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne:
			OutJsonObj->SetField("someOperatorOne", PragmaJson::StructToJsonValue(*OneOf.Union.SomeOperatorOne.GetTypedPtr()));
			break;
		case EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne:
			OutJsonObj->SetField("someServiceOne", PragmaJson::StructToJsonValue(*OneOf.Union.SomeServiceOne.GetTypedPtr()));
			break;
		default:
			break;
	}
	// Per protobuf spec, it's ok to have empty oneof.
	return true;
}
bool FPragma_PlayerData_PlayerDataRequestProto_Payload::DeserializeFromParentJson(const TSharedRef<FJsonObject>& JsonObj, void* OutValue)
{
	FPragma_PlayerData_PlayerDataRequestProto_Payload& OutOneOf = static_cast<FPragma_PlayerData_PlayerDataRequestProto*>(OutValue)->Payload;
	if (JsonObj->HasField("addNumber"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumber;
		new(OutOneOf.Union.AddNumber.GetTypedPtr()) FPragma_PlayerData_AddNumberRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_AddNumberRequestProto>(JsonObj->TryGetField(TEXT("addNumber")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("addNumberTimesTwo"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::AddNumberTimesTwo;
		new(OutOneOf.Union.AddNumberTimesTwo.GetTypedPtr()) FPragma_PlayerData_AddNumberTimesTwoRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_AddNumberTimesTwoRequestProto>(JsonObj->TryGetField(TEXT("addNumberTimesTwo")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("bigDataEntity"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::BigDataEntity;
		new(OutOneOf.Union.BigDataEntity.GetTypedPtr()) FPragma_PlayerData_BigDataRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_BigDataRequestProto>(JsonObj->TryGetField(TEXT("bigDataEntity")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("contentDrivenGrants"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ContentDrivenGrants;
		new(OutOneOf.Union.ContentDrivenGrants.GetTypedPtr()) FPragma_PlayerData_ContentDrivenGrantsRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_ContentDrivenGrantsRequestProto>(JsonObj->TryGetField(TEXT("contentDrivenGrants")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("deleteNumberData"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DeleteNumberData;
		new(OutOneOf.Union.DeleteNumberData.GetTypedPtr()) FPragma_PlayerData_DeleteNumberDataRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_DeleteNumberDataRequestProto>(JsonObj->TryGetField(TEXT("deleteNumberData")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("demoContentOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::DemoContentOperation;
		new(OutOneOf.Union.DemoContentOperation.GetTypedPtr()) FPragma_PlayerData_DemoContentOperationRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_DemoContentOperationRequestProto>(JsonObj->TryGetField(TEXT("demoContentOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echo"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::Echo;
		new(OutOneOf.Union.Echo.GetTypedPtr()) FPragma_PlayerData_EchoRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoRequestProto>(JsonObj->TryGetField(TEXT("echo")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echoComplex"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoComplex;
		new(OutOneOf.Union.EchoComplex.GetTypedPtr()) FPragma_PlayerData_EchoComplexRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoComplexRequestProto>(JsonObj->TryGetField(TEXT("echoComplex")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("echoList"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EchoList;
		new(OutOneOf.Union.EchoList.GetTypedPtr()) FPragma_PlayerData_EchoListRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EchoListRequestProto>(JsonObj->TryGetField(TEXT("echoList")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("emptyOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::EmptyOperation;
		new(OutOneOf.Union.EmptyOperation.GetTypedPtr()) FPragma_PlayerData_EmptyOperationRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_EmptyOperationRequestProto>(JsonObj->TryGetField(TEXT("emptyOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("grantStarterItems"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::GrantStarterItems;
		new(OutOneOf.Union.GrantStarterItems.GetTypedPtr()) FPragma_PlayerData_GrantStarterItemsRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_GrantStarterItemsRequestProto>(JsonObj->TryGetField(TEXT("grantStarterItems")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("hideStuffFromPlayer"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::HideStuffFromPlayer;
		new(OutOneOf.Union.HideStuffFromPlayer.GetTypedPtr()) FPragma_PlayerData_PlayerHiddenComponentRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_PlayerHiddenComponentRequestProto>(JsonObj->TryGetField(TEXT("hideStuffFromPlayer")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("loadTestEntityTransform"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::LoadTestEntityTransform;
		new(OutOneOf.Union.LoadTestEntityTransform.GetTypedPtr()) FPragma_PlayerData_LoadTestEntityTransformRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_LoadTestEntityTransformRequestProto>(JsonObj->TryGetField(TEXT("loadTestEntityTransform")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("manyComponentEntity"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::ManyComponentEntity;
		new(OutOneOf.Union.ManyComponentEntity.GetTypedPtr()) FPragma_PlayerData_ManyComponentRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_ManyComponentRequestProto>(JsonObj->TryGetField(TEXT("manyComponentEntity")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("myOperation"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::MyOperation;
		new(OutOneOf.Union.MyOperation.GetTypedPtr()) FPragma_PlayerData_MyChecklistRequestOneProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_MyChecklistRequestOneProto>(JsonObj->TryGetField(TEXT("myOperation")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("sendEmptyPayload"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SendEmptyPayload;
		new(OutOneOf.Union.SendEmptyPayload.GetTypedPtr()) FPragma_PlayerData_SendEmptyPayloadRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SendEmptyPayloadRequestProto>(JsonObj->TryGetField(TEXT("sendEmptyPayload")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("someOperatorOne"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeOperatorOne;
		new(OutOneOf.Union.SomeOperatorOne.GetTypedPtr()) FPragma_PlayerData_SomeOperatorRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SomeOperatorRequestProto>(JsonObj->TryGetField(TEXT("someOperatorOne")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	if (JsonObj->HasField("someServiceOne"))
	{
		OutOneOf.Type = EPragma_PlayerData_PlayerDataRequestProto_PayloadType::SomeServiceOne;
		new(OutOneOf.Union.SomeServiceOne.GetTypedPtr()) FPragma_PlayerData_SomeServiceRequestProto(PragmaJson::JsonValueToStruct<FPragma_PlayerData_SomeServiceRequestProto>(JsonObj->TryGetField(TEXT("someServiceOne")).ToSharedRef()));
		return true; // return to short circuit any other checks.
	}
	// Per protobuf spec, oneofs have _at most_ one of the fields. None set is valid, so we always return true.
	return true;
}

bool operator==(const FPragma_PlayerData_PlayerDataRequestProto_Payload& Lhs, const FPragma_PlayerData_PlayerDataRequestProto_Payload& Rhs)
{
	return Lhs.Equals(Rhs);
}
bool operator!=(const FPragma_PlayerData_PlayerDataRequestProto_Payload& Lhs, const FPragma_PlayerData_PlayerDataRequestProto_Payload& Rhs)
{
	return !(Lhs == Rhs);
}


bool FPragma_PlayerData_PlayerDataRequestProto::AddonSerializer(const void* Value, TSharedRef<FJsonObject>& OutJsonObj)
{
	bool Success = true;
	Success &= FPragma_PlayerData_PlayerDataRequestProto_Payload::SerializeIntoParentJson(Value, OutJsonObj);
	return Success;
}

bool FPragma_PlayerData_PlayerDataRequestProto::AddonDeserializer(const TSharedRef<FJsonObject>& JsonObj, void* OutValue)
{
	bool Success = true;
	Success &= FPragma_PlayerData_PlayerDataRequestProto_Payload::DeserializeFromParentJson(JsonObj, OutValue);
	return Success;
}

bool operator==(const FPragma_PlayerData_PlayerDataRequestProto& Lhs, const FPragma_PlayerData_PlayerDataRequestProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.Payload == Rhs.Payload
;
}
bool operator!=(const FPragma_PlayerData_PlayerDataRequestProto& Lhs, const FPragma_PlayerData_PlayerDataRequestProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_MyLiveDataComponentProto& Lhs, const FPragma_PlayerData_MyLiveDataComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
			&& Lhs.SomeNumber == Rhs.SomeNumber
;
}
bool operator!=(const FPragma_PlayerData_MyLiveDataComponentProto& Lhs, const FPragma_PlayerData_MyLiveDataComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}


bool operator==(const FPragma_PlayerData_PlayerHiddenComponentProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentProto& Rhs)
{
	return true // Initial true allows simpler codegen.
;
}
bool operator!=(const FPragma_PlayerData_PlayerHiddenComponentProto& Lhs, const FPragma_PlayerData_PlayerHiddenComponentProto& Rhs)
{
	return !(Lhs == Rhs);
}
