// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaAccountCommonDto.h"
#include "Dto/PragmaDataRightsCommonDto.h"
#include "Dto/PragmaFriendCommonDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaPresenceExtDto.h"

#include "PragmaFriendRpcDto.generated.h"

// Forward declarations.
struct FPragma_Friend_PresenceUpdateV1Notification;
struct FPragma_Friend_FriendUpdateV1Notification;
struct FPragma_Friend_FriendListUpdateV1Notification;
struct FPragma_Friend_IntegrationTestDeleteFriendDataV1Response;
struct FPragma_Friend_IntegrationTestDeleteFriendDataV1Request;
struct FPragma_Friend_SetPresenceV1Response;
struct FPragma_Friend_SetPresenceV1Request;
struct FPragma_Friend_RemoveFriendV1Response;
struct FPragma_Friend_RemoveFriendV1Request;
struct FPragma_Friend_RespondToFriendInviteV1Response;
struct FPragma_Friend_RespondToFriendInviteV1Request;
struct FPragma_Friend_GetFriendListV1Response;
struct FPragma_Friend_GetFriendListV1Request;
struct FPragma_Friend_SendFriendInviteBySocialIdV1Response;
struct FPragma_Friend_SendFriendInviteBySocialIdV1Request;
struct FPragma_Friend_SendFriendInviteV1Response;
struct FPragma_Friend_SendFriendInviteV1Request;

//
// Source protos:
// pragma/friend/friendRpc.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_PresenceUpdateV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Friend_Presence NewPresence;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_PresenceUpdateV1Notification& Lhs, const FPragma_Friend_PresenceUpdateV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_PresenceUpdateV1Notification& Lhs, const FPragma_Friend_PresenceUpdateV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_FriendUpdateV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString SocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Friend_Presence UpdatedPresence;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_FriendUpdateV1Notification& Lhs, const FPragma_Friend_FriendUpdateV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_FriendUpdateV1Notification& Lhs, const FPragma_Friend_FriendUpdateV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_FriendListUpdateV1Notification
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Friend_FriendListUpdates Updates;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_FriendListUpdateV1Notification& Lhs, const FPragma_Friend_FriendListUpdateV1Notification& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_FriendListUpdateV1Notification& Lhs, const FPragma_Friend_FriendListUpdateV1Notification& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_IntegrationTestDeleteFriendDataV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_IntegrationTestDeleteFriendDataV1Response& Lhs, const FPragma_Friend_IntegrationTestDeleteFriendDataV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_IntegrationTestDeleteFriendDataV1Response& Lhs, const FPragma_Friend_IntegrationTestDeleteFriendDataV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_IntegrationTestDeleteFriendDataV1Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_Friend_IntegrationTestDeleteFriendDataV1Request& Lhs, const FPragma_Friend_IntegrationTestDeleteFriendDataV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_IntegrationTestDeleteFriendDataV1Request& Lhs, const FPragma_Friend_IntegrationTestDeleteFriendDataV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SetPresenceV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SetPresenceV1Response& Lhs, const FPragma_Friend_SetPresenceV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SetPresenceV1Response& Lhs, const FPragma_Friend_SetPresenceV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SetPresenceV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString BasicPresence;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Presence_ExtRichPresence Ext;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SetPresenceV1Request& Lhs, const FPragma_Friend_SetPresenceV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SetPresenceV1Request& Lhs, const FPragma_Friend_SetPresenceV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_RemoveFriendV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_RemoveFriendV1Response& Lhs, const FPragma_Friend_RemoveFriendV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_RemoveFriendV1Response& Lhs, const FPragma_Friend_RemoveFriendV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_RemoveFriendV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString FriendSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_RemoveFriendV1Request& Lhs, const FPragma_Friend_RemoveFriendV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_RemoveFriendV1Request& Lhs, const FPragma_Friend_RemoveFriendV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_RespondToFriendInviteV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_RespondToFriendInviteV1Response& Lhs, const FPragma_Friend_RespondToFriendInviteV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_RespondToFriendInviteV1Response& Lhs, const FPragma_Friend_RespondToFriendInviteV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_RespondToFriendInviteV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviterSocialId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	bool AcceptInvite{false};

};
PRAGMASDK_API bool operator==(const FPragma_Friend_RespondToFriendInviteV1Request& Lhs, const FPragma_Friend_RespondToFriendInviteV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_RespondToFriendInviteV1Request& Lhs, const FPragma_Friend_RespondToFriendInviteV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_GetFriendListV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Friend_FriendList FriendList;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_GetFriendListV1Response& Lhs, const FPragma_Friend_GetFriendListV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_GetFriendListV1Response& Lhs, const FPragma_Friend_GetFriendListV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_GetFriendListV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString GameShardId;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_GetFriendListV1Request& Lhs, const FPragma_Friend_GetFriendListV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_GetFriendListV1Request& Lhs, const FPragma_Friend_GetFriendListV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SendFriendInviteBySocialIdV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SendFriendInviteBySocialIdV1Response& Lhs, const FPragma_Friend_SendFriendInviteBySocialIdV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SendFriendInviteBySocialIdV1Response& Lhs, const FPragma_Friend_SendFriendInviteBySocialIdV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SendFriendInviteBySocialIdV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString InviteeSocialId;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SendFriendInviteBySocialIdV1Request& Lhs, const FPragma_Friend_SendFriendInviteBySocialIdV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SendFriendInviteBySocialIdV1Request& Lhs, const FPragma_Friend_SendFriendInviteBySocialIdV1Request& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SendFriendInviteV1Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString Response;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SendFriendInviteV1Response& Lhs, const FPragma_Friend_SendFriendInviteV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SendFriendInviteV1Response& Lhs, const FPragma_Friend_SendFriendInviteV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Friend_SendFriendInviteV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Account_DisplayName InviteeDisplayName;

};
PRAGMASDK_API bool operator==(const FPragma_Friend_SendFriendInviteV1Request& Lhs, const FPragma_Friend_SendFriendInviteV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Friend_SendFriendInviteV1Request& Lhs, const FPragma_Friend_SendFriendInviteV1Request& Rhs);

