// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"

#include "PragmaFleetRpcDto.generated.h"

// Forward declarations.
struct FPragma_Fleet_ReportCapacityV1Response;
struct FPragma_Fleet_ReportCapacityV1Request;

//
// Source protos:
// pragma/fleet/fleetRpc.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Fleet_ReportCapacityV1Response
{
	GENERATED_BODY()

	UPROPERTY()
	int64 NextHeartbeatPeriodMillis{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> GameInstanceIds;

};
PRAGMASDK_API bool operator==(const FPragma_Fleet_ReportCapacityV1Response& Lhs, const FPragma_Fleet_ReportCapacityV1Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Fleet_ReportCapacityV1Response& Lhs, const FPragma_Fleet_ReportCapacityV1Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Fleet_ReportCapacityV1Request
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ServerId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ServerPoolId;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 TotalCapacity{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	int32 UsedCapacity{0};

};
PRAGMASDK_API bool operator==(const FPragma_Fleet_ReportCapacityV1Request& Lhs, const FPragma_Fleet_ReportCapacityV1Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Fleet_ReportCapacityV1Request& Lhs, const FPragma_Fleet_ReportCapacityV1Request& Rhs);

