// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaInventoryCommonDto.h"
#include "Dto/PragmaInventoryContentDto.h"
#include "Dto/PragmaInventoryRpcDto.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaGameDataExtDto.h"

#include "PragmaGameDataRpcDto.generated.h"

// Forward declarations.
struct FPragma_GameData_InventoryContent;
struct FPragma_GameData_InventoryLoginData;
struct FPragma_GameData_LoginDataV3;
struct FPragma_GameData_GetLoginDataV3Response;
struct FPragma_GameData_GetLoginDataV3Request;

//
// Source protos:
// pragma/gamedata/gameDataRpc.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_GameData_InventoryContent
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_Inventory_ItemCatalog ItemCatalog;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Inventory_AnnotatedStore> Stores;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Inventory_UpdateEntry> UpdateEntries;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Inventory_CraftingEntry> CraftingEntries;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Inventory_ItemBundle> ItemBundles;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FPragma_Inventory_ProviderEntitlement> ProviderEntitlements;

};
PRAGMASDK_API bool operator==(const FPragma_GameData_InventoryContent& Lhs, const FPragma_GameData_InventoryContent& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_GameData_InventoryContent& Lhs, const FPragma_GameData_InventoryContent& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_GameData_InventoryLoginData
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	TArray<FString> IssuedLimitedGrantTrackingIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_GameData_InventoryContent InventoryContent;

};
PRAGMASDK_API bool operator==(const FPragma_GameData_InventoryLoginData& Lhs, const FPragma_GameData_InventoryLoginData& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_GameData_InventoryLoginData& Lhs, const FPragma_GameData_InventoryLoginData& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_GameData_LoginDataV3
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_GameData_ExtLoginData Ext;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_GameData_InventoryLoginData InventoryData;

};
PRAGMASDK_API bool operator==(const FPragma_GameData_LoginDataV3& Lhs, const FPragma_GameData_LoginDataV3& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_GameData_LoginDataV3& Lhs, const FPragma_GameData_LoginDataV3& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_GameData_GetLoginDataV3Response
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FPragma_GameData_LoginDataV3 LoginData;

};
PRAGMASDK_API bool operator==(const FPragma_GameData_GetLoginDataV3Response& Lhs, const FPragma_GameData_GetLoginDataV3Response& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_GameData_GetLoginDataV3Response& Lhs, const FPragma_GameData_GetLoginDataV3Response& Rhs);

USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_GameData_GetLoginDataV3Request
{
	GENERATED_BODY()

};
PRAGMASDK_API bool operator==(const FPragma_GameData_GetLoginDataV3Request& Lhs, const FPragma_GameData_GetLoginDataV3Request& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_GameData_GetLoginDataV3Request& Lhs, const FPragma_GameData_GetLoginDataV3Request& Rhs);

