// <auto-generated>
//      Generated by Pragma Platform protoc-custom-plugins sdk-unreal4 target.  DO NOT EDIT!
//      Source template: unreal4/Dto.h.mustache
// </auto-generated>
#pragma once

#include "CoreMinimal.h"
#include "Dom/JsonObject.h"
#include "Dto/PragmaTypesDto.h"
#include "Dto/PragmaOptionsDto.h"
#include "Dto/PragmaPartyRpcExtDto.h"

#include "PragmaMatchmakingExtDto.generated.h"

// Forward declarations.
struct FPragma_Matchmaking_ExtMatchmakingKey;

//
// Source protos:
// shared/matchmakingExt.proto
//


USTRUCT(BlueprintType, Category=Pragma)
struct FPragma_Matchmaking_ExtMatchmakingKey
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ExampleString;

	UPROPERTY()
	int64 ExampleLong{0};

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category=Pragma)
	FString ExampleProto;

};
PRAGMASDK_API bool operator==(const FPragma_Matchmaking_ExtMatchmakingKey& Lhs, const FPragma_Matchmaking_ExtMatchmakingKey& Rhs);
PRAGMASDK_API bool operator!=(const FPragma_Matchmaking_ExtMatchmakingKey& Lhs, const FPragma_Matchmaking_ExtMatchmakingKey& Rhs);

